### ISSUE TITLE
 resize: Resize icon does not appear after first resize. 

### ISSUE THREAD

**Issue by dr-robertk** [compiz-reloaded/compiz#102]
After resizing a window the resize icon only appears when the cursor is on the decoration within the previous size of the window. This may be related to #85. This occurs in compiz-0.8.14 and I haven't tested the master branch.

I'm happy to provide a fix if pointed to the places (such as resize.c) where the problem may occur. 

Thanks for consideration and great that someone is maintaining the project.

**Comment by soreau** [comment]
Does this happen with both gtk-window-decorator and emerald or just one?

**Comment by dr-robertk** [comment]
Thanks for the quick reply. I'm using gt-window-decorator with gtk2. I'll test emerald and report back. I did a bit more investigation. The resize icon does not completely vanish. It just shows for what the old window rectangle.

**Comment by soreau** [comment]
Does it happen with all windows? Which version of compiz are you using?

**Comment by dr-robertk** [comment]
I also tested with the master and it showed the same behaviour. From what I can tell it happens with all windows, i.e. browser window, xterm etc. For gtk-window-decorator the resize cursor vanishes on the right and lower edge whereas for emerald this only happens on the lower edge. I also replaces the resize.c file with an old version from 0.8.8 where it uses to work and it didn't change anything so the problems seems to be more in updating some components to the new size of the window. Unfortunately, I don't know the code to make any more useful suggestions. I'll add some pics to explain.

**Comment by soreau** [comment]
I thought I had seen something like this, now I am able to reproduce with the default gtk-w-d theme. However using marco support and loading the Numix theme, the problem seems to disappear altogether. Does it happen if you load a theme with e.g. `gtk-window-decorator --marco-theme Numix --replace`

**Comment by dr-robertk** [comment]
I'll check. I might have compiled with macro support.

**Comment by dr-robertk** [comment]
Using the Numix theme also solves the problem here.

**Comment by dr-robertk** [comment]
Actually, it only works sometimes. For some windows I don't see the resize icons on the right and lower border after I created the window. I'll double check to be sure.

**Comment by soreau** [comment]
So the bug is when using the static hard coded cairo theme and most likely somewhere in [gtk-window-decorator.c](https://github.com/compiz-reloaded/compiz/blob/master/gtk-window-decorator/gtk-window-decorator.c)

**Comment by dr-robertk** [comment]
With Numix it works except for uxterm. I have no idea why that should not work. All other windows seem to work properly. I can have a look in gtk-window-decorator.c and I'll report back when I found something useful. Thanks for the hint.

**Comment by dr-robertk** [comment]
So far I have not discovered anything and after a diff with the old 0.8.8. version I didn't see any suspicious things in gtk-window-decorator.c  . If I choose some random gtk themes from the https://www.gnome-look.org/ then sometimes the same problems occurs. For that reason I starting to believe the problem may not be in gtk-window-decorator.c 

Once a resize is done the resize mouse icons disappears. If the window is not touched for some time then at some point the mouse icons will reappear and work correctly. So I was wondering what kind of state update that is and where I should look for it?

**Comment by soreau** [comment]
I still think the problem is likely in gtk-window-decorator (search for 'cursor') though it's not impossible to be elsewhere. Regarding diffing, does the problem not happen with 0.8.8?

**Comment by dr-robertk** [comment]
Thanks for the hint. I'll look into it.

**Comment by dr-robertk** [comment]
I haven't made much progress, but I can report that the event_filter_func function that would call a resize is not triggered when the mouse cursor is moved over the right boundary after a resize was done. It seems that for some reasons the event windows are not updated correctly after a resize. However, the . I haven't yet fully understood how that all plays together.  I guess the problem must be somewhere in update_event_windows.

**Comment by soreau** [comment]
That sounds plausible, maybe update_event_windows is just getting/setting wrong width/height, possibly when it calls whichever get_event_window_position is actually called. I noticed theme_get_event_window_position is set to get_event_window_position if the static cairo theme is being used.  Also could be a libwnck bug, this is speaking only looking at the code, not actually debugging anything.

**Comment by dr-robertk** [comment]
I was thinking the same, that maybe width and height are mixed up with x and y coordinates but I haven't found evidence yet. I'll do some more digging.

**Comment by dr-robertk** [comment]
I wasn't getting anywhere that's why I bisected the repo. The faulty behaviour was introduced in commit 875c9d773345e8a3a2ec640665ffd801ac860817 (Added support for 2D decorations). The resize icons etc. appear correctly with the code compiled from one commit before. I looked at the diff but it may take some more time to figure things out.

**Comment by dr-robertk** [comment]
@soreau : My guess is that the problem is related to the change of the data layout in libdecoration/decoration.c where a 

data[1] = decoration type

was introduced and then all other contents shifted one position. Somewhere the old layout is used which is why the sizes don't match. Just a guess though.

**Comment by dr-robertk** [comment]
Ok, forget the above comment. The problem is "fixed" when I revert this line in gtk-window-decorator.c (line 7584) to what it was before commit  143b8dad03e8c35efa2a415c71c8e6aa6aea2f04.

works:
    frame_window_atom  = XInternAtom (xdisplay, "_NET_FRAME_WINDOW", FALSE);

seems to be the problem: 
    frame_window_atom = XInternAtom (xdisplay, DECOR_INPUT_FRAME_ATOM_NAME, FALSE);

@soreau Could you comment on that?

**Comment by soreau** [comment]
@dr-robertk Why do you put "fixed" in quotation marks? I tested this and it does indeed fix the problem. If it doesn't break anything else I'd be happy to accept a pull request for this patch.

**Comment by dr-robertk** [comment]
I said "fixed" because it may very well break something else depending on the theme used. I'll put up a PR for maybe others to discuss the patch. Thanks for the comments.

**Comment by dr-robertk** [comment]
Fixed in commit 1d65d3cf8d42fd8c44dc76a480f671c841d3d67f.
