### ISSUE TITLE
How to debug compiz crash

### ISSUE THREAD

**Issue by alekseyt** [compiz-reloaded/compiz#105]
This is a question. I have installed compiz-reloaded 0.8.14 and sometimes i observe compiz crashes. From my experimenting i know that i crashes probably somewhere in animations (doesn't reproduce w/o animations plugin disabled), but i couldn't locate exact place of the crash.

I have also enabled "Crash Handler" plugin and after every crash it creates a file in /tmp with content like this:

```
Reading symbols from compiz...done.
Attaching to program: /usr/bin/compiz, process 30186
(gdb) (gdb) (gdb) 
(gdb) 
(gdb) (gdb)
```

I also have compiz not stripped:

```
$ file /usr/bin/compiz
/usr/bin/compiz: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=d8c422fe84adc0a5257b8845c5b706dbdb89fca5, with debug_info, not stripped
```

I tried to do ``ulimit -c unlimited`` and launch compiz from terminal, but it doesn't produce core, it says "Launching fallback window manager" instead.

What am i doing wrong? How do i produce stack trace?

I can launch compiz with any options or recompile with different flags if needed.

**Comment by soreau** [comment]
This might have to do with your system disallowing gdb attach to process as user. If this is the problem, you should be able to temporarily disable it with `echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope`

**Comment by alekseyt** [comment]
Thanks, i can see stack trace now. Any suggestions how to enable source code line numbers in it?

Right now i have stack trace like this:

```
#7  0x0000555d9ff8448e in enableTexture ()
#8  0x0000555d9ff9f169 in drawWindowTexture ()
#9  0x00007fa712d1e169 in  () at /usr/lib/compiz/libanimation.so
#10 0x00007fa72081a251 in decorDrawWindow () at /usr/lib/compiz/libdecoration.so
#11 0x0000555d9ff9f9e9 in paintWindow ()
```

CFLAGS="-g -ggdb" or is there another way to achieve the this?

**Comment by soreau** [comment]
Yes, I think you have to enable debug symbols and setting CFLAGS at configure time is probably the best way.

**Comment by alekseyt** [comment]
Thank you very much.
