### ISSUE TITLE
Create demo image for trying Compiz

### ISSUE THREAD

**Issue by hubslave** [compiz-reloaded/compiz#108]
It is not very easy to get Compiz running (need to build, configure it and replace current window manager). Therefore it would be convenient for new users if a virtualbox image / livecd / installation iso based on some distro was provided.

**Comment by rabin-io** [comment]
Are you talking about testing the latest code ? or just play around with compiz ? if you are looking just to test compiz use a distro like Fedora MATE which with compiz pre-installed.

**Comment by hubslave** [comment]
Ok, I didn't know about that one. Yes, I was thinking mostly about the play around case.
It would be nice to add a link to it (e.g. in the wiki or readme).
Then this issue could be closed.
