### ISSUE TITLE
Command entered in “Commands” not work

### ISSUE THREAD

**Issue by geremi1** [compiz-reloaded/compiz#119]
I had created a new script called “.brightness.sh” and put it in the $PATH, so I can execute it like this:”.brightness -1 -d” (to decrease the brightness of screen 1). When I tapped it directly in the Terminal, it works, but not at all when doing the combination (Super+D). How can I fix this??? (Would like to have solve this for Wednesday breakfast please :)

**Comment by rabin-io** [comment]
try to use the pull path to the script.

**Comment by soreau** [comment]
I think @rabin-io meant 'full' path to script.

**Comment by geremi1** [comment]
Yes

**Comment by geremi1** [comment]
I tested it now, it doesn’t work

**Comment by rabin-io** [comment]
is execution bits are set on the script ? 

    chmod +x  brightness.sh

**Comment by soreau** [comment]
If you put a line in the script such as 'echo "test" > /tmp/test' does /tmp/test get created on keybinding?

**Comment by soreau** [comment]
In your initial command ”.brightness -1 -d” the leading '.' looks suspicious

**Comment by geremi1** [comment]
Yes, execute for everybody is there

**Comment by geremi1** [comment]
The ‘.’ is only for the script to not be list in normal configuration Thundar

**Comment by geremi1** [comment]
@soreau no, doesn’t do anything

**Comment by soreau** [comment]
Assuming you put the echo statement unconditionally in the script, this means the script wasn't called. Try copying the script to /usr/local/bin/brightness (try without the dot in case this is the problem) and eliminate the args (integrate them into the script, in case that has something to do with it) and try with the full path.

**Comment by soreau** [comment]
Alternatively, start with a simple script in that only runs touches a file so you can see if it was called. After the file is created on keybinding, you can go from there.

**Comment by geremi1** [comment]
Ok, I’ll test that
