### ISSUE TITLE
Multi-touch Compiz Plugin

### ISSUE THREAD

**Issue by Eignar17** [compiz-reloaded/compiz#16]
add plugin of list in compiz-reloaded
info:
https://jamcnaughton.com/2010/05/20/how-to-install-the-compiz-multi-touch-plugin/

view plugin:
https://www.youtube.com/watch?v=rY-85BUqWgY

**Comment by zezic** [comment]
+1 for this

**Comment by Eignar17** [comment]
@soreau add is plugin?
