### ISSUE TITLE
Stereo 3D Plugin for Compiz

### ISSUE THREAD

**Issue by Eignar17** [compiz-reloaded/compiz#17]
add plugin of list in compiz-reloaded
info:https://launchpad.net/compiz-plugin-stereo3d

view plugin:
https://www.youtube.com/watch?v=g7eOICtovNs

**Comment by XRevan86** [comment]
That plugin is for Compiz 0.9.x.

**Comment by Eignar17** [comment]
@ddudek plugin stereo3d port to compiz 0.8

**Comment by Eignar17** [comment]
@matijaskala port to compiz 0.8 please
