### ISSUE TITLE
tuxfamily compiz repository for debian testing is out-of-sync

### ISSUE THREAD

**Issue by igor-liferenko** [compiz-reloaded/compiz#19]
Hi,

I installed Debian stretch amd64, built 2016-06-13, from http://cdimage.debian.org/cdimage/weekly-builds/amd64/jigdo-dvd/debian-testing-amd64-DVD-1.jigdo.

I tried to install compiz this way:

    wget -q http://download.tuxfamily.org/compiz/apt/key.pub -O- | sudo apt-key add -
    sudo sh -c 'echo deb http://download.tuxfamily.org/compiz/debian stretch main >> /etc/apt/sources.list'
    sudo apt-get update
    sudo apt-get install compiz compiz-mate

But I got this error:

    The following packages have unmet dependencies:
     compiz : Depends: compiz-gtk (>= 0.8.12.3-0~stretch2) but it is not going to be installed
     compiz-mate : Depends: compiz-gtk (= 0.8.12.3-0~stretch2) but it is not going to be installed
    E: Unable to correct problems, you have held broken packages.

Regards,
Igor

**Comment by XRevan86** [comment]
@elgeneralmidi, poke.

**Comment by hugh-m** [comment]
The instructions on Soreau's blog no longer work, also. Would someone kindly provide the steps for building and installation from the Github source. I was very pleased to find Compiz-reloaded, and am anxious to get it going on my Debian/Sid/MATE installation.

**Comment by soreau** [comment]
@hugh-m The blog states that the script is designed for ubuntu, your mileage may vary with other distributions. To install compiz, you clone, build and install each component in the correct order.

There is also http://compiz-debian.tuxfamily.org/ that might be a better option for you.

**Comment by hugh-m** [comment]
Thanks for your reply. That's what I need help with. I am fine with the cloning, but need help with the build/install. Specifically, what are the dependencies, or how to determine the dependencies. Also, what is the "correct order" (if not obvious).

I gather from your tone that this should be fairly easy. But it doesn't matter how easy something is if you haven't done it at least once. It's still a mystery.

**Comment by soreau** [comment]
You can see the [script set here](http://git.northfield.ws/compiz/?p=compiz/scripts;a=tree) for reference. The dependency list is in the prerequisites file, the order is the components array in the INSTALL file. All of the components use the format `./autogen.sh --prefix=$prefix && make && sudo make install` with the exception of ccsm (and fusion-icon) which use `./setup.py build --prefix=$prefix && sudo ./setup.py install [--install-layout=deb] --prefix=$prefix`

**Comment by hugh-m** [comment]
Thanks. I'll try it.

**Comment by XRevan86** [comment]
@elgeneralmidi, I got a report that compiz-gtk is not rebuilt targeting Marco/Gtk3 on Debian testing.
