### ISSUE TITLE
Whisker Menu Resize Bug

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [compiz-reloaded/compiz#20]
When you resize the whisker menu in XFCE with Compiz Reloaded running it decides to act wacky and take up the full screen (sometimes more than the full screen). This can then only be fixed by switching back to xfwm4 and then back to Compiz when you've resized it to the size you want.

**Comment by ShadowKyogre** [comment]
Heya @KUPOinyourWINDOW. What plugins do you have currently enabled? I'll try to reproduce it in my testing VM.

**Comment by ShadowKyogre** [comment]
@KUPOinyourWINDOW :  Writing back here to say that both @soreau and I've reproduced your issue with a clean config.

**Comment by ethus3h** [comment]
I don't use Xfce or Arch so IDK if this works or is related to this bug, but someone posted this in #compiz on Freenode: https://aur.archlinux.org/packages/xfce4-panel-compiz/

**Comment by kn00tcn** [comment]
uhh did this get fixed then unfixed? is xfce or whisker supposed to make a change instead?

good thing the menu constrains itself back to the screen size on the second opening...

**Comment by KUPOinyourWINDOW** [comment]
It got fixed really fast kn00tcn and it's still working fine for me. Can you give more details on what you're experiencing or head in to the irc chat and speak to one of the devs themselves?

**Comment by kn00tcn** [comment]
if i click whisker's resize triangle, it takes up more than full screen like you said

when i look at the code tab here, i can see the commit, then a revert, then a second attempt, then a revert of the second attempt, therefore the fix isnt in the code anymore

now that i look closer, fedora's version is 0.8.12.3, does that mean the precompiled distro version is a year old now?

**Comment by KUPOinyourWINDOW** [comment]
I just resized the whisker menu with compiz reloaded enabled, the patch is still there, or at the very least isn't needed anymore as everything is working fine for me.

I should add, I am running the master branch. Which one are you using?

**Comment by kn00tcn** [comment]
i thought ubuntu uses compiz 0.9, this github is for 0.8, or do you mean you're compiling it yourself from the source files here

**Comment by KUPOinyourWINDOW** [comment]
This project, Compiz Reloaded, is a continuation of the 0.8 version found here. I'm talking about and using Compiz Reloaded. For me it's working fine!

I used in terminal: git clone git://northfield.ws/compiz/scripts (without the -b release-0.8.12)
then ran the "go" script with ./scripts/go

So long as you're using Compiz Reloaded, not compiz 0.9 from the Ubuntu repos, maybe that'll fix it for you?
