### ISSUE TITLE
Can we have an option for msaa?

### ISSUE THREAD

**Issue by nicman23** [compiz-reloaded/compiz#21]
I would really like to have a 3d obj as my wallpaper but the jaggies are too much

**Comment by soreau** [comment]
Can you post a screenshot? MSAA should be handled by the graphics driver, check the settings. Which driver/card are you using?

**Comment by nicman23** [comment]
radeonsi / gallium/ mesa. I cannot force msaa through them.
[https://imgur.com/e4ifAlt](Example)

**Comment by soreau** [comment]
Maybe try driconf setting for GL_MAX_SAMPLES

**Comment by nicman23** [comment]
While this does work, it affects fonts and basically everything else.

**Comment by soreau** [comment]
Proper support would require implementing it in cubemodels which isn't planned so I'm closing this for now.

**Comment by nicman23** [comment]
ok thanks anyways

**Comment by kn00tcn** [comment]
we can load 3d models as a wallpaper!?

but if they're not actually animating, what is the point... if static, just pre-render them somewhere in great quality into a static image

**Comment by soreau** [comment]
I believe the reference is to cubemodel plugin, with transparent cube while not rotating, in essence drawing as wallpaper.

**Comment by kn00tcn** [comment]
oh right, 3d stuff hmm.... what i would do is use SMAA (or FXAA) instead since it would be a lightweight post process shader
