### ISSUE TITLE
Adding --zcomp flag for compositing only

### ISSUE THREAD

**Issue by punk0x29a** [compiz-reloaded/compiz#22]
Hi there! It's a copy of a question I've posted on launchpad a while ago, but it seems to be dead over there... 

> I love Compiz very much, especially Zoom feature and some smooth transitions between windows. It's really good for my eyes.
> However, I also like tiling window managers, and I'm currently using Awesome WM for the great amount of control it's internal Lua scripting gives me.
> 
> I'd like to ask if it'd be possible to implement --zcomp flag, as in here:
> https://gitlab.com/dmorris/zcomp
> 
> Demo: https://www.youtube.com/watch?v=hxpzNGppcbs
> 
> The code provided on gitlab page is for older version of Compiz. I tried to port it into 9* series, but too much stuff has changed when it comes to grabbing the input ( and I'm not so good at c++, too. Also, original zcomp code uses nasty goto hack, forbidden in newer standard ).
> So far I've been able to launch it with compositing transparency enabled, but no joy - WM workspaces and focusing clients don't work, rendering whole thing useless.
> 
> I believe that --zcomp flag should be implemented in new Compiz releases. It'd help a lot of people and it'd tremendously increase Compiz popularity, making it even grater than it is right now.
> 
> Thanks!

**Comment by soreau** [comment]
This is the first I've ever heard of zcomp or a request for its functionality. We have no plans for this.
