### ISSUE TITLE
Odd GTK mixture w/Marco GTK3 build

### ISSUE THREAD

**Issue by ShadowKyogre** [compiz-reloaded/compiz#23]
So I encountered this when trying to build against a GTK+3 build of Marco. See this for more info: https://ptpb.pw/RP8q/text

~~But more important is the fact that non-marco support is broken (no titlebar).~~

Steps to reproduce:

1. Clone repo
2. `NOCONFIGURE=1 ./autogen.sh`
3. `./configure --enable-gtk --disable-marco`
4. `make`
5. `cd gtk-window-decorator/`
6. `./gtk-window-decorator --replace`

Expected result: Some garish, simple window decorator.

Actual result: No titlebar, no nothing.

~~So I was wondering: Is the broken non-marco support intentional for gtk-window-decorator since we already have emerald?~~

[EDIT]: Just remember to run compiz before running the decorator.

**Comment by ShadowKyogre** [comment]
For the odd mixture build:

0. Install a GTK3 build of marco
1. Clone repo
2. `./autogen.sh`
3. `./configure --enable-marco`
4. `make`
5. `cd gtk-window-decorator/`
6. `./gtk-window-decorator --replace`

You should get a segfault about a mixture of GTK2 and GTK3 in the build.

**Comment by XRevan86** [comment]
> --enable-gtk=3.0

```--enable-gtk --with-gtk=3.0```

**Comment by XRevan86** [comment]
> --enable-gtk=3.0

```--enable-gtk --with-gtk=3.0```

Some garish, simple window decorator I do see :-).

**Comment by ShadowKyogre** [comment]
@XRevan86 : Okay, there we go. I'm guessing the decorator was run without Compiz itself.

Man my mind is fuzzy on holidays.

For future reference (in case anyone needs to build it against a GTK3 Marco), copypasting this from private chat: `./configure --enable-gtk --with-gtk=3.0 --enable-marco`
