### ISSUE TITLE
Firefox needs to be unmaxised after launching

### ISSUE THREAD

**Issue by nicman23** [compiz-reloaded/compiz#25]
If it starts maximised then, the window doesn't update.

However, it's still responsive.

**Comment by ethus3h** [comment]
Oh! I think this might be the same issue as in #26 that I just added.

**Comment by ethus3h** [comment]
@nicman23, Are you using Plasma 5? Do you have Plasma's taskbar thumbnails enabled? Thanks :)

**Comment by nicman23** [comment]
No i'm using mate 1.15 and as a workaround, I have firefox to discard (and not save) the session on closing it.

**Comment by raveit65** [comment]
Important question: are you talking about firefox gtk3 with gtk+-3.20.x ?
...this is a well known mess :)

**Comment by nicman23** [comment]
yes sorry, arch firefox default is built with gtk3

**Comment by ethus3h** [comment]
Oh, is the window contents just not redrawing (and still showing the contents), as opposed to a blank (white/black) display? I'm thinking now that this is a different bug from #26, which I can work around by disabling Plasma taskbar thumbnails. (I have seen it happen sometimes where the window contents aren't redrawn, but I can still see what was there before, and I think that might be this bug.)

**Comment by ethus3h** [comment]
I've seen the not-redrawing issue with Hexchat too, now...

**Comment by nicman23** [comment]
Firefox 48 fixed this
