### ISSUE TITLE
Some KDE apps start in full screen

### ISSUE THREAD

**Issue by ethus3h** [compiz-reloaded/compiz#27]
I'm running into this bug as reported at https://bugs.launchpad.net/ubuntu/+source/compiz/+bug/329337

Using Okular 0.24.2  / KDE Development Platform 4.14.20.

From the Launchpad bug report:

"Whenever I open a close a maximized (not full-screen) document in okular, then open any other document (not necessarily the one I had open), the document now opens in full-screen mode 100% of the time. Nearly all of the time, the toolbar is missing as well, even though I have never told okular not to display the toolbar and I rarely use full-screen mode intentionally. Okular should remember the previous display state and preferences, including whether it was full-screen or not and whether it was displaying the toolbar or not, so I don't have to reset these things every time I open it

I'm using Ubuntu 8.10, okular 4:4.1.4-0ubuntu1~intrepid1. I've been experiencing this problem for about the past month or two. I don't think this occurred in earlier versions of okular. It doesn't happen in any other applications I'm aware of."

**Comment by ethus3h** [comment]
This appears to affect Kontact too.

**Comment by ethus3h** [comment]
This issue does not affect Openbox.

**Comment by ethus3h** [comment]
Un-full-screening Okular (which starts in full screen like this) fairly regularly (~50% of the time??) crashes X11 and/or SDDM (I assume X11, but recover from it by running systemctl start sddm). I'm not sure whether this crashing is a compiz-reloaded problem or not.

**Comment by soreau** [comment]
It would be nice to have a test case that doesn't involve kde-specific applications and that is reliably reproducible.

**Comment by ethus3h** [comment]
The opens-in-fullscreen issue is consistently reproducible with Okular (KDE SC 4 PDF viewer), KOrganizer (calendar), and Dolphin (file manager). The issue is that if the last window closed was maximized when it was closed, it will be in full screen when the app is re-opened.

KDE Frameworks 5 apps don't appear to have the problem.

Catia (a non-KDE Qt 4 app) doesn't show the problem, and Calligra Sheets, a spreadsheet app built using the KDE SC 4 library, does not have the problem.

**Comment by ethus3h** [comment]
The crash does not appear to be an issue with Compiz, as it also affects Openbox.

Opening in fullscreen, though, does seem to be specific to Compiz, because it does not affect Openbox.

**Comment by ethus3h** [comment]
I suspect this is related: when opening Dolphin if the window size it tries to create is taller than the display's space, it will be vertically-maximized so it can't be resized without unmaximizing it first. (That's another thing, when a window is maximized it cannot be resized, e.g. with the resize binding. This is annoying.)

**Comment by ethus3h** [comment]
Something's fixed this. I wonder if it was fixed incidentally by the grid bugfixes regarding saving and restoring maximize state? Anyway, closing it. Thanks!

**Comment by ethus3h** [comment]
(The issues mentioned in https://github.com/compiz-reloaded/compiz/issues/27#issuecomment-303223945 still happen, but that really belongs in a separate issue, I think.)
