### ISSUE TITLE
Bug: Title bars don't always refresh window names when they change.

### ISSUE THREAD

**Issue by ethus3h** [compiz-reloaded/compiz#30]
I'm not sure whether this is related to #25, nor have I figured out how to reproduce it reliably yet.

**Comment by ethus3h** [comment]
Or, perhaps, whether it should be filed against Emerald (that's the decorator I'm using).

**Comment by soreau** [comment]
Does this happen with other window managers? The title should be set by the application.

**Comment by ethus3h** [comment]
I've never seen it with Openbox. I'm going to close it for now until I have steps to repro, I think…
