### ISSUE TITLE
compiz with debian stretch

### ISSUE THREAD

**Issue by gaetanov62** [compiz-reloaded/compiz#31]
after adding the below repository:
wget -q http://download.tuxfamily.org/compiz/apt/key.pub -O- | apt-key add - && echo "deb http://download.tuxfamily.org/compiz/debian $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/compiz-debian.list && apt-get update
works fine with jessie but does'nt work with debian stretch, I got error message for damaged packages certainly for missing dependencies.

**Comment by XRevan86** [comment]
@elgeneralmidi, stretch gives problems again :-).

**Comment by gaetanov62** [comment]
Any plan for a solution?

Il 30/lug/2016 10:51, "Alexei Sorokin" <notifications@github.com> ha
scritto:

**Comment by gaetanov62** [comment]
SOLVED - I've added repository as described in tuxfamily site 
<http://compiz-debian.tuxfamily.org/>, next i've installed compiz-core 
(not compiz) and related dependencies and plugins, also installed 
fuson-icon and ccsm, to make ccsm working I've modified it replacing Gtk 
2.0 version with Gtk 3.0 version as shown below:

gi.require_version('Gtk', '2.0')
gi.require_version('Gdk', '2.0')
from gi.repository import Gtk, Gdk
if Gtk.check_version(3, 0, 0) is None:
     gi.require_version('GdkX11', '2.0')

gi.require_version('Gtk', '3.0')
gi.require_version('Gdk', '3.0')
from gi.repository import Gtk, Gdk
if Gtk.check_version(3, 0, 0) is None:
     gi.require_version('GdkX11', '3.0')

finally I've used emerald as theme manager.

That's all.


Il 30/07/2016 10:51, Alexei Sorokin ha scritto:

**Comment by elgeneralmidi** [comment]
@gaetanov62 Thanks for the bug report, today i've rebuild compiz, it's fixed now :)
http://compiz-debian.tuxfamily.org/changelog.html

@XRevan86 You can close the issue ;)
