### ISSUE TITLE
Plasma 5 panel autohide is broken

### ISSUE THREAD

**Issue by ethus3h** [compiz-reloaded/compiz#32]
Plasma 5 panel autohide is broken: the panels are always visible, even when set to autohide, and just sit on top of maximised windows.

**Comment by ethus3h** [comment]
This issue also affects Openbox.

**Comment by nicman23** [comment]
do previews work?

**Comment by ethus3h** [comment]
Yes, now that I have switched to the Nouveau drivers. They didn't work with the Nvidia drivers.

**Comment by soreau** [comment]
Another case of kde not playing nicely with compiz. Closing for now.
