### ISSUE TITLE
graphics tearing, not refreshed display segments

### ISSUE THREAD

**Issue by rhoit** [compiz-reloaded/compiz#33]
I'm on archlinux and updated all compiz package on 2016-Aug-06, using yaourt/aur,
which updated compiz-core of version `compiz-core-git-0.8.10.r6.gb1aea52` to `compiz-core-git-0.8.12.3.r35.gef9f4fa`. 

Problem occurs on random windows never noticed on `firefox`, `gnome-terminal`.

1. First began on `emacs` although I though, it was due to change config file.
2. I noticed same thing `thunderbird` and finally stop fiddling with emacs config.
3. looked at system update log and found a update of intel graphics
    xf86-video-intel (1:2.99.917+668+gc28e62f-1 -> 1:2.99.917+676+g26f8ab5-1)
    thought it was the culprit because  following the update DRI3 is now default , from DRI2
4. finally today I loaded `metacity --replace` to find  no tearing at all.

Although I narrow it down to compiz, this problem may not created by compiz alone.
Here are the snaps of my window taking screenshots isn't helping (fixes the problem except for emacs).

![screenshot88](https://cloud.githubusercontent.com/assets/1684754/17641123/1a46c774-6133-11e6-98f2-d15881a74da8.png)

![screenshot93](https://cloud.githubusercontent.com/assets/1684754/17641124/2a44fd8a-6133-11e6-8835-3986d43ebef7.png)

![screenshot94](https://cloud.githubusercontent.com/assets/1684754/17641132/7475759c-6133-11e6-8f75-0060bbddb002.png)

![screenshot95](https://cloud.githubusercontent.com/assets/1684754/17641133/7cddc892-6133-11e6-9abb-93e1c56abc7c.png)

![screenshot96](https://cloud.githubusercontent.com/assets/1684754/17641134/81b65a32-6133-11e6-8ad1-e33d9756a145.png)

same above situation with screenshot..

![screenshot_2016-08-13_08-30-27](https://cloud.githubusercontent.com/assets/1684754/17641146/c53b7f1c-6133-11e6-93d9-8f9866ca5ebc.png)

**Comment by soreau** [comment]
Does it make a difference if you try the modesetting driver instead of
intel? Something like:

Section "Device"
    Identifier "Intel"
    Driver "modesetting"
EndSection

with xf86-video-modesetting installed.

**Comment by rhoit** [comment]
Can't find package for Archlinux, seem like there use to be "xf86-video-modesetting" package earlier they have pull it out for some reason.

**Comment by soreau** [comment]
>
> Can't find package for Archlinux, seem like there use to be
> "xf86-video-modesetting" package earlier they have pull it out for some
> reason.
>

My mistake, should be included with xorg-server, so it's probably already
available.

**Comment by rhoit** [comment]
@soreau thanks, "xf86-video-modesetting" fixed the problem.  :checkered_flag:  :checkered_flag:
