### ISSUE TITLE
Window manager: Compatibility request: Add support for KWin/Plasma animated window moving/resizing

### ISSUE THREAD

**Issue by ethus3h** [compiz-reloaded/compiz#35]
Window manager: Compatibility request: Add support for KWin/Plasma animated window moving/resizing

(This is used, for example, when switching between different submenus in the Application Menu, or between different windows' thumbnails in the Plasma task switcher — the menu or thumbnail seems to be the same window, and it gets moved and resized as needed, which is animated in KWin but seems choppy in Compiz-Reloaded.)

**Comment by ethus3h** [comment]
This is similar to #32, and possibly fixing this will also fix that.

**Comment by ethus3h** [comment]
In addition, clicks to Plasma notifications aren't received, making it impossible to close them.

**Comment by soreau** [comment]
I think this is a case of kde not playing nicely with compiz and that is unlikely to change. Closing for now.
