### ISSUE TITLE
Drawing using the annotate plugin causes glitchy behaviour of shadows (they change to black and look weird and such).

### ISSUE THREAD

**Issue by ethus3h** [compiz-reloaded/compiz#36]
Drawing using the annotate plugin causes glitchy behaviour of shadows (they change to black and look weird and such).

Using the Emerald theme linked in this comment: https://github.com/compiz-reloaded/emerald/issues/12#issuecomment-236392358 .

Possibly related to that issue?

**Comment by soreau** [comment]
I can't reproduce this. Perhaps a driver issue?

**Comment by ethus3h** [comment]
Ah, not sure. I'll have a computer with Intel drivers in a bit, so I can see if it happens then. Thanks! :)

**Comment by soreau** [comment]
Closing for now
