### ISSUE TITLE
Compiz's edge flipping/bindings no longer work

### ISSUE THREAD

**Issue by stratact** [compiz-reloaded/compiz#39]
I can't drag my windows across viewports, even have the following settings enabled:
* `Desktop Wall>Edge Flipping>Edge Flip Move`
* `Desktop Wall>Bindings>Edge flipping>*`

The functionality had previous worked in version 0.8.12, before I moved to using the upstream git packages.

@soreau on IRC, hunches it's when the `Desktop Wall` plugin was moved from plugins-main to core.

**Comment by soreau** [comment]
Thanks for catching this. I've bisected it to [c093054](https://github.com/compiz-reloaded/compiz/commit/c0930542fe10c191fb65f0185572bd322a855a57), will look into it further.

**Comment by soreau** [comment]
I was able to get it working after resetting the configuration by clicking ccsm>Preference>'Reset to defaults' button, and reconfiguring ccsm.
I believe there is an obscure long-standing bug, though hard to reproduce. It can happen when using an older config with newer binaries. Nearly impossible to reproduce, manifesting itself in bizarre ways, making it a difficult debug target.

**Comment by stratact** [comment]
Same with me, but I had issues with resetting to defaults, so I manually removed the config files and start over again with `ccsm`. Things are now working like I expect. Thanks for looking into it @soreau!
