### ISSUE TITLE
GTK+-3.21.x desktop redraw issues

### ISSUE THREAD

**Issue by raveit65** [compiz-reloaded/compiz#40]
Sadly it looks like that compiz and emerald are broke by this gtk+ commit.
https://bugzilla.gnome.org/show_bug.cgi?id=768415
https://git.gnome.org/browse/gtk+/commit/?id=2c7b21718f18ab743cd79784ae28cad582f58503
If i enable compiz the desktop goes black and don't redraw any more.
![bildschirmfoto zu 2016-09-05_17-49-15](https://cloud.githubusercontent.com/assets/961604/18267888/8cd050de-7421-11e6-8ff2-02199120e8c6.png)
Enable the wallpaper plugin and a 'killall caja' can be used as workaround, than the desktop icons are there and we have no redraw issue.
First analysis from Luke who fixes the problem in caja:
https://github.com/mate-desktop/caja/issues/604#issuecomment-244797723

```
Are you running these tests with caja 1.15.4? If you did and got icons on the desktop over Compiz's wallpaper you just found a substantial difference between compiz 0.8 and 0.9. In compiz 0.9 the wallpaper is rendered on top the desktop, covering up icons even if the desktop itself is transparent. If Marco is working and compiz 0.8 is not, look for a forced native window somewhere in the compiz 0.8 code, maybe that was something the Ubuntu devs took out in the refactor and rewrite to C++ for 0.9
```

@XRevan86 
Can you please take a look into it, this is really a breaker for the fedora Mate-compiz spin.

**Comment by raveit65** [comment]
I forgot, this was the terminal out put with ccsm after i added a wallpaper with the plugin but before 'killall caja'
```
 (ccsm:29981): Gtk-CRITICAL **: gtk_cell_renderer_render: assertion 'GTK_CELL_RENDERER_GET_CLASS (cell)->render != NULL' failed
(ccsm:29981): Gtk-CRITICAL **: gtk_cell_renderer_render: assertion 'GTK_CELL_RENDERER_GET_CLASS (cell)->render != NULL' failed
```

**Comment by raveit65** [comment]
Same problem if i compile emerald with gtk2, so the issue might be in compiz itself.

**Comment by raveit65** [comment]
more infos:
This was the fix for caja https://github.com/mate-desktop/caja/pull/602 for the same problem.

**Comment by gaetanov62** [comment]
On my Debian Stretch with gtk 3.22.1-1 and Compiz enabled, Caja 1.16.0 works properly but desktop redrawing problem remains. Without Compiz and enabling Marco everything is ok. Any solution?

**Comment by raveit65** [comment]
Workaround is mentioned in first comment.

**Comment by nicman23** [comment]
but is there any solution? I like having caja manage my desktop ..

**Comment by gaetanov62** [comment]
There is a workaround using wallpaper plugin of compiz (I have caja 1.16
also).

Il 15/ott/2016 10:59, "nicman23" <notifications@github.com> ha scritto:

**Comment by nicman23** [comment]
yes sorry mb, i though you needed to disable caja's 'show desktop' like you had to do in gnome 2, for the wallpaper plugin to work. 

but... you don't, so i deleted my comment :P

**Comment by ruegerjr** [comment]
If it helps, I notice that on arch linux, using their latest PKGBUILD, I don't get this bug if caja-gtk3 1.16 is built while gtk3-3.20 is in use while building, even if I then upgrade gtk3 to 3.22 afterwards.

**Comment by bidzapfc** [comment]
Is some fix viable? Would it be pushed?

**Comment by XRevan86** [comment]
@bidzapfc, nothing's yet ready. I'm working on it.

**Comment by lukefromdc** [comment]
This is exactly the same issue Nemo had for years with compiz 0.9 builds, but which was somehow resolved a while back.  Some change was made probably in compiz 0.9 itself but the changelog stops at 2011 and I have no real way to find it.

There was a patched version of Nemo for compiz for a while that reverted the transparent desktop and forced drawing of the background, and it works. This suggests a change for Caja in which the noncomposited background drawing case for GTK 3.22 could be forced. Currently the desktop is transparent (like nemo and nautilus) when compositing is detected, while when compositing is not used the desktop image is copied from what mate-settings-daemon draws and drawn again. Not the best use of RAM but it works for noncompositing WM's and may work here too. Adding an option to force the noncomposited case would work unless the new code (copied from Nautilus) does not work with compiz-reloaded for some reason.

Has anyone tested compiz-reloaded with current Nautilus and GTK 3.22? 

I have compiz 0.9 installed and thus cannot easily test this myself.

**Comment by lukefromdc** [comment]
A possible workaround if compiz 0.8 always draws the wallpaper from the wallpaper plugin underneath the desktop icons might be to set that option, pick a wallpaper, then use a script to start compiz, kill it, and restart it at every session startup. No hackier than the timing games I have to play to get compiz 0.9 to work in Debian Unstable, where it otherwise works fine with Caja but if started at the wrong part of the session startup can't read its configuration or start the decorator.

**Comment by XRevan86** [comment]
> Has anyone tested compiz-reloaded with current Nautilus and GTK+ 3.22?

Actually, the fix that was done in Nautilus/Nemo and Caja is what causes this problem with Compiz Reloaded %).

**Comment by lukefromdc** [comment]
Changes are cooking for Caja that should fix this. New background drawing code, affects three packages.
 
https://github.com/mate-desktop/caja/pull/731
and related 
https://github.com/mate-desktop/mate-settings-daemon/pull/169
https://github.com/mate-desktop/mate-desktop/pull/249

**Comment by raveit65** [comment]
With Mate-1.18 release all is fixed.
Backports for 1.16 comming soon.
