### ISSUE TITLE
Fast alt tab with mesa-git freezes Compiz (0.8.12.3)

### ISSUE THREAD

**Issue by nicman23** [compiz-reloaded/compiz#43]
I 'm using static application switcher and mesa-git on mate de on arch 64.

Fast alteration between windows completely freezes Compiz to the point that -15 does not kill it. Compiz with --debug does not print anything else except that it cannot find plugins in my home (because they are installed system wide). This is probably a mesa problem, but there are no other crashes with other applications and this is my main pc with which i game daily both on wine and other native applications. Need git versions because of a radeonsi regression

This again happens only with this plugin. Killing it with -9 and replacing with marco, my session is not affected - everything is there.

Dmesg does not report anything, neither does journalctl

I am on a gcn 1.0 card (7700m) - radeonsi. Please help me to provide you with logs or dumps.

**Comment by soreau** [comment]
@nicman23 Hi, sounds like you should report this as a mesa bug for radeonsi. This isn't a problem with compiz.

**Comment by nicman23** [comment]
will do thanks

**Comment by viktorstrate** [comment]
It happends on nvidia drivers too
