### ISSUE TITLE
Feature request: option for cleaner appearance when moving

### ISSUE THREAD

**Issue by ethus3h** [compiz-reloaded/compiz#48]
I'd love to have an option for drawing a solid semi-transparent background (like is drawn for snapping windows to a grid by dragging to the edges) instead of window contents when moving, for easier positioning relative to windows underneath it.

**Comment by ethus3h** [comment]
And related, configurable resize outline thickness analogous to this PR: https://github.com/compiz-reloaded/compiz-plugins-extra/pull/7/files

**Comment by soreau** [comment]
This is not planned for implementation.

**Comment by ethus3h** [comment]
@soreau, should I understand that as meaning that pull requests implementing it won't be accepted?

**Comment by soreau** [comment]
You can make a pull request if you'd like.
