### ISSUE TITLE
Pb mouse cursors when Size or Theme changes

### ISSUE THREAD

**Issue by tititopher68** [compiz-reloaded/compiz#5]
HI, 

In XFCE, issue with mouse cursors when size or themes changes. It's necessary to  kill compiz and reload it for the change to be effective. (Sorry for my bas english, but french...)

**Comment by raveit65** [comment]
Did you build compiz with libcompizconfig as build dependency?

**Comment by tititopher68** [comment]
Hi,


Yes, and i tested also with these packets on :
http://compiz-debian.tuxfamily.org/....Same issue...(My config DEBIAN
Jessie 8.4 + XFCE4). I have read somethings about the same issue but with
compiz-core  0.9.12.2-02122016 (ubuntu Launchpad.net compiz...i
know....ubuntu....).

Best regards

Christophe

2016-03-30 13:56 GMT+02:00 Wolfgang Ulbrich <notifications@github.com>:

**Comment by raveit65** [comment]
Do you have a link to 0.9 report?

**Comment by tititopher68** [comment]
Branch 0.9 Compiz : issue : LP #1359211 - mouse cursors when Size or Theme
changes

https://bugs.launchpad.net/ubuntu/+source/compiz/+bug/86184

https://launchpad.net/ubuntu/wily/+source/compiz/+changelog

https://launchpadlibrarian.net/228213671/compiz_0.9.12.2+15.10.20151202-0ubuntu1.diff.gz

and the fix is : to use compiz cursorCache to get properly updated cursors
(LP:
    #1359211)

Best regards,

Christophe

2016-03-30 14:45 GMT+02:00 Wolfgang Ulbrich <notifications@github.com>:

**Comment by raveit65** [comment]
Can you change the cursor settings with ccsm/general plugin?

**Comment by XRevan86** [comment]
@tititopher68, does 867bc2c help the issue?

**Comment by XRevan86** [comment]
I'll assume it does.
