### ISSUE TITLE
Missing an actual compositor

### ISSUE THREAD

**Issue by Pival81** [compiz-reloaded/compiz#52]
Hi, I've been having this problem with compiz-reloaded, with either xfce4 and mate1.16.1:

![schermata a 2016-11-13 17-10-55](https://cloud.githubusercontent.com/assets/15673222/20247097/206d140c-a9c5-11e6-9b1d-f81ed2cedc7b.png)

This doesn't occur with compiz 0.9, because it has the "compositing" plugin.
Why isn't this plugin integrated in compiz-reloaded?
Also, don't know if it's related, dockbarx doesn't show any previews even when using compiz (of course i've enabled the option, it just shows empty space instead of the actual preview)

**Comment by ethus3h** [comment]
The compositing is always enabled in Compiz-Reloaded, it just isn't a separate plugin like it is in Compiz-0.9.

**Comment by Pival81** [comment]
@ethus3h then what is the problem with that bug?

**Comment by ethus3h** [comment]
I'm not sure what's causing that glitch in the screenshot. If disabling the "Compositing" plugin in Compiz 0.9 makes the glitch appear, it's possible that Compiz-Reloaded isn't starting properly; to check that you can run `compiz --replace` (assuming `compiz` is your compiz-reloaded) in a terminal and see what it says…

**Comment by Pival81** [comment]
Ok, i'll try, but only once my laptop works, it left us this morning...
Maybe i can try on my dad's pc.

**Comment by kn00tcn** [comment]
did you ever try it? https://github.com/compiz-reloaded/compiz/issues/56 duplicate sections of windows like that are usually driver bugs that may or may not be fixable

**Comment by soreau** [comment]
Probably the same issue described in #56, a probable driver bug.
