### ISSUE TITLE
Edge flip not working

### ISSUE THREAD

**Issue by thr23** [compiz-reloaded/compiz#54]
Can't drag windows between the workspaces, and can't flip workspaces with a mouse pointer, even with respective edge_flip options in cube rotate plugin enabled. Tried in Xfce and MATE.

**Comment by soreau** [comment]
Make sure rotate_flip_left/right_edge are set to respective edges in ccsm>Rotate Cube>Bindings>Rotate Cube>Rotate Flip Left/Right.

**Comment by thr23** [comment]
Yes, that's it. Please consider defining sane defaults for these bindings (left and right screen edges, respectively). I think this used to work OOTB.

**Comment by soreau** [comment]
https://github.com/compiz-reloaded/compiz/commit/06ed24f5c8dc78e20a71d6b57a235ac954e8872a
