### ISSUE TITLE
Rendering artifacts in Seamonkey in Fedora 25, Xfce, Xorg, 

### ISSUE THREAD

**Issue by yarda** [compiz-reloaded/compiz#56]
Originally reported in https://bugzilla.redhat.com/show_bug.cgi?id=1409385 the problem manifests in seamonkey (seamonkey-2.40-9.fc25.x86_64, also tried version 2.46 with the same results). Reproducer:

1. run seamonkey
2. search any string in google
3. scrol down and up

The artifacts disappear after alt+tab or printscreen. Sometimes it seems the web content isn't just updated and alt+tab fix it. Artifacts can be seen on scrollbar, taskbar, menubar and also in the web content. Firefox (which IMHO use the same core) renders correctly without artifacts. Reproduced on laptop with Intel video SNA driver.

compiz-0.8.12.3-3.fc25.x86_64

Tried various combinations of workarounds (workarounds plugin) in ccsm, but none seems to help.

It worked OK on the same machine on F24. Hopefully I will be able to bisect later.

Rendering articacts of web content (text twice, missing text) and scrollbar:
![20170101_001](https://cloud.githubusercontent.com/assets/958845/21606218/4628cc7a-d1ae-11e6-9b22-e49427283b8e.jpg)

Details of rendering artifacts of scrollbar (more precisely the scrollbar leaves traces when it moves), (the image was rotated during upload by -90 degrees):
![20170101_002](https://cloud.githubusercontent.com/assets/958845/21606248/679d9c82-d1ae-11e6-9c3b-bde93423057a.jpg)

**Comment by yarda** [comment]
I don't know whether other applications are also affected.

**Comment by ethus3h** [comment]
I'm inclined to think that this is either related to GPU driver bug or to GTK3 bug, but because Seamonkey appears to be built using GTK2, I suspect it is a GPU driver bug. What brand GPU do you use, and what driver do you use for it?

**Comment by yarda** [comment]
It seems to be related to Intel GPU driver bug. The Xorg-1.19.1-1.fc25 switched to xf86-video-modesetting driver and the problem wasn't reproducible but Xorg-1.19.1-2.fc25 switched back to xf86-video-intel in f25 (probably due to some problem with Chrome) and the problem is back. I verified it by switching between xf86-video-intel and xf86-video-modesetting by hand.

I am going to bisect the xf86-video-intel driver to find out whether it's really problem with the driver (I am curious :), but it seems so. However, the xf86-video-intel will be probably dropped in favour of xf86-video-modesetting, so maybe it will resolve by itself :)

**Comment by soreau** [comment]
I think it's probably a driver bug as well, can't reproduce here.
