### ISSUE TITLE
Compiz has a circular build dependency

### ISSUE THREAD

**Issue by pwanchope** [compiz-reloaded/compiz#58]
To build compiz fully I need libcompizconfig.  To build libcompizconfig I need compiz.

Currently, I have to build compiz, build libcompizconfig and then rebuild compiz to get gwd shadow control through the decoration plugin.  This is not ideal.

There are a few ways to resolve this:

1.  Move libcompizconfig into the compiz package.
2.  Move gwd into a separate package (the shadow options could be moved into the mate-compat plugin)
3.  Move the shadow options out of ccsm.  They're only used by gwd and that has options that you have to access through dconf editor anyway.  It would be much better to have them all in one place; either gsettings or ccsm.

**Comment by XRevan86** [comment]
No more compizconfig in gtk-window-decorator, no more suffering.

**Comment by raveit65** [comment]
@XRevan86 
> No more compizconfig in gtk-window-decorator, no more suffering.

What is the solution? Or did i mss something?

**Comment by XRevan86** [comment]
@raveit65, the D-Bus support in gtk-window-decorator has been fixed.
