### ISSUE TITLE
Window contents are not always updated

### ISSUE THREAD

**Issue by ethus3h** [compiz-reloaded/compiz#62]
I see this sometimes, where windows don't redraw until they're resized.

See similar issues #25 (specific to Firefox) and #30 (which I think was just me not noticing it wasn't just the title bars that were frozen).

I, just now, saw it after restarting emerald: possibly a correlation?

**Comment by kn00tcn** [comment]
i'm not sure i've ever seen this, what about the various compiz plugins potentially interfering?

**Comment by ethus3h** [comment]
Here's my config as of a few days ago:

[2017mar28-copied-2017apr05a06.profile.txt](https://github.com/compiz-reloaded/compiz/files/901733/2017mar28-copied-2017apr05a06.profile.txt)

**Comment by kn00tcn** [comment]
how often is 'sometimes'? would be nice to have a use case that happens often enough

my only emerald problem is it crashing when using the animated switcher

**Comment by ethus3h** [comment]
This happens maybe one in five times that I open Firefox (built with GTK2).

**Comment by ethus3h** [comment]
I wonder if this is related to a problem I've been having for the past few weeks where GTK+ 2 apps have a problem where only parts of the windows are redrawn. It seems to only happen when I'm using Compiz; I don't see it under Openbox (not now anyway; I don't remember if I have ever in the past). I'm using an Intel GPU. Screenshots:

- [Firefox (1)](https://archive.org/download/Screenshot2017.04.0902.00.01/Screenshot_2017.04.09_02.00.01.png)
- [HexChat](https://archive.org/download/Screenshot2017.04.0902.00.01/Screenshot_2017.04.09_02.00.50.png)
- [Firefox (2)](https://archive.org/download/Screenshot2017.05.3014.57.47/Screenshot_2017.05.30_14.57.47.png)

**Comment by kn00tcn** [comment]
if that recently appeared, you must have had a kernel or mesa update, since artifacts like that look like gpu driver bugs

when i moved to mesa17, i have full screen blocky artifacts, the compiz code had not changed

**Comment by ethus3h** [comment]
Ah, that would be a mesa update then (haven't updated the kernel since around Sept. 2016). Probably not related to this issue. Thanks @kn00tcn! :)

**Comment by kn00tcn** [comment]
wtf? kernel updates have security fixes

**Comment by ethus3h** [comment]
I just saw the issue with Firefox for the first time ever **in Openbox**. That means this isn't specific to Compiz.

(I'm assuming the weird artifacts are something else — Mesa, kernel, or whatever, even though they don't happen with Openbox.)

I'll close this... sorry for the noise.

**Comment by soreau** [comment]
I've seen this before too, especially when first starting compiz. It's often coupled with invisible windows. A minimize/restore of affected windows usually fixes it. It's difficult to reproduce so not easy to debug and I don't know what might cause it.

**Comment by ethus3h** [comment]
I don't remember ever having noticed invisible windows...
