### ISSUE TITLE
Please Rename The Project

### ISSUE THREAD

**Issue by tarakbumba** [compiz-reloaded/compiz#65]
On a distro which provides Compiz 0.9.x, Compiz 0.8.x and Compiz 0.9.x conflicts and sometimes, like in Mageia, it's replaced by Compiz 0.9.x unless some blacklisting had done. Also, it is impossible to have both even testing purposes. I merely recommend that rename all project something else than compiz, may be Beryl again? Then it can be installed side by side with compiz and conflictions may avoided.

**Comment by nick87720z** [comment]
Though i'm unaffected... Yet might be compiz-legacy, compiz-sunset, beryl-reborn, aquamarine, morganite. Finally, compiz-reloaded as well :).

**Comment by soreau** [comment]
Thanks for the suggestions. It is possible to have both installed, though not likely using a package manager. One can install any version of compiz to a nonstandard prefix and setup an environment to run it. The project is not likely to be renamed for several reasons, probably the biggest is because it's a lot of unnecessary work.

**Comment by tarakbumba** [comment]
Tough this issue is closed i would like to add some of my opinions.  I mean when i open this issue, completely renaming references from compiz  and libdecoration to anything else. It is not realistic to install this project non standard paths, these paths must be added common path to a user able to run it. Also, that is not a much work. I do it, for the sake to rename compiz to beryl, just using a few lines of sed and file tricks in [my rpm spec files](https://github.com/tarakbumba/RPMSPecs/tree/master/beryl) 

Renaming the project/components will allow proper packaging without conflicting with Compiz, allow users not to confuse with Compiz. Also, renaming will allow you to not stuck with 0.8.x versioning scheme. Anyway, glad to see that you give a breath of life to Compiz 0.8.x. Thank you all for your hard work.
