### ISSUE TITLE
gtk-window-decorator + marco theme: No visible buttons, appart Close

### ISSUE THREAD

**Issue by nick87720z** [compiz-reloaded/compiz#66]
When use-marco-theme is enabled, i have only name and close button.
though without marco i have well-known windows-like layout, regardless of marco configuration in dconf.

Issue happens immediately when theming is enabled, gwd restart doesn't help.
When i start it in terminal, i get info about one button disabled:
`gtk-window-decorator: Ignoring unknown or already-used button name "appmenu"`
_(since i use vala-panel-appmenu, which is not only for vala-panel)._

Using gentoo, and compiz - from this overlay:
https://github.com/kajzersoze/compiz-reloaded-overlay

**Enabled features**: cairo compizconfig dbus gsettings gtk gtk3 inotify marco svg
**Disabled**: -fuse -mate

**Comment by XRevan86** [comment]
You can define the desired button layout with "--button-layout": ```--button-layout 'close,minimize,maximize:'```

**Comment by nick87720z** [comment]
I exactly:
```
$ gtk-window-decorator --button-layout "close,minimize,maximize:"
gtk-window-decorator: Ignoring unknown or already-used button name "appmenu"
```
Doesn't help, still only name text and close button.
Yet, since gwd theme is affected by marco config, i expected its button layout affected as well.

**Comment by nick87720z** [comment]
How it looks with vertex theme:
https://ibin.co/3EVa76TRm6A2.png
