### ISSUE TITLE
Consider marco settings, when it is installed.

### ISSUE THREAD

**Issue by nick87720z** [compiz-reloaded/compiz#67]
I just discovered source of button-layout in dconf. Its value was: appmenu:close, just as in #66 ,
thus vala-panel-appmenu does nothing there
...found it casually, searching for completely another thing.
Though gwd needs marco for theming, and theme name is taken from schema org.mate.marco.general,
button-layouts, for example, is taken from org.gnome.desktop.wm.preferences.

I'm not sure about this change, at least after unsuccessful attempt to try simply
`$ marco --replace`
when it failed, complaining about missing mate-related schema... don't know, how much this is important.

**Comment by XRevan86** [comment]
Does c134ef5 do the trick for ye?

**Comment by nick87720z** [comment]
Yeah, thanks. Now it is controlled by marco's scheme.
