### ISSUE TITLE
libmarco-private is now gtk3+, gtk-window-decorator can't draw gtk2.0 in the same time

### ISSUE THREAD

**Issue by azisnaufal** [compiz-reloaded/compiz#69]
I'm running ubuntu 16.04 and mate 1.18 (which is all of mate component is now gtk3.0+).
Marco and compiz run perfectly, but gtk-window-decorator doesn't.
I use this ppa to install compiz on my machine : https://launchpad.net/~adamsmith/+archive/ubuntu/compiz-reloaded 
and this ppa to install mate 1.18 : 
https://launchpad.net/~jonathonf/+archive/ubuntu/mate-1.18
The installation is run perfectly without any problem. except compiz-mate.
compiz-mate need libmarco-private0. but the ppa only provide libmarco-private1.

I patch the deb file of compiz-mate, and edit the DEBIAN/control file. I change the depends of libmarco-private0 to libmarco-private1. Repack and install it. The installation has no any problem.

Then I ran compiz and the gtk-window-decorator, the gtk-window-decorator throw this :

oazisn@oazisn:~/Downloads$ gtk-window-decorator --replace
gtk-window-decorator: error while loading shared libraries: libmarco-private.so.0: cannot open shared object file: No such file or directory

so i link the libmarco-private.so.1 to libmacro-private.so.1 . And then i re-ran the gtk-window-decorator. The gtk-window-decorator throw a breakpoint.

(gtk-window-decorator:7311): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
Trace/breakpoint trap (core dumped)

so, any bugfixes for the new marco with gtk3?

**Comment by raveit65** [comment]
You need to rebuild compiz with 
configure --with-gtk=3.0
against new marco.
So compiling it in a right way is the bugfix ;-)
