### ISSUE TITLE
Debian package building with checkinstall causes conflicts with other compiz packages

### ISSUE THREAD

**Issue by djbarney** [compiz-reloaded/compiz#7]
I successfully installed compiz-reloaded although checkinstall does not always find the correct name (which should be the the directory name after git clone). I thought I'd uninstalled all previous compiz packages but Ubuntu tries to update the compiz-reloaded one's. I "held" the packages using apt which worked for a while, but I'd missed the fusion-icon package (yes, no compiz in the title) and on a system update this installed all sorts of compiz stuff that completely broke compiz-reloaded. After rooting out all the Ubuntu repository packages I should no longer have the problem.

I'll try and look into how to include Debian package stuff in the build process that checkinstall can use, or even just make a debian/ubuntu package as part of the build process. A Reloaded debian package should flag other compiz installs as a conflict and refuse to install or ask to remove them.

**Comment by XRevan86** [comment]
What is the issue exactly?
That @elgeneralmidi's repository doesn't take Ubuntu's Compiz packages into account?
