### ISSUE TITLE
gtk-window-decorator not possible to theme

### ISSUE THREAD

**Issue by gianlucapettinello** [compiz-reloaded/compiz#70]
I tried to install compiz 0.8 series in Arch. Currently I have compiz 0.9 series but I see that compiz 0.8 is way faster and frankly I prefer C over C++.

Unfortunately gtk-window-decorator doesn't take the metacity theme.

In arch wiki they say it is necessary to define the key in gconftool-2:
gconftool-2 -s /apps/metacity/general/theme -t string theme-name
No success.
I see that compiz 0.8 prefers marco over metacity. I'm using compiz within xfce.

Please help me!
Thanks
Gianluca

**Comment by IKRadulov** [comment]
In compiz reloaded the theme feature is supported by marco ,not metacity. If you build compiz reloaded with marco gtk2 or gtk3 then you need to set marco theme in org.mate.Marco.general theme (done with dconf or gsettings). Also make sure that org.compiz-0.gwd use-marco-theme is set to true.
To build it with marco theme support edit the compiz-core-git pkg with _use_marco = 1 (for marco gtk3) or 2 (for marco gtk2).

**Comment by XRevan86** [comment]
```gtk-window-decorator --marco-theme "theme-name" --button-layout "https://github.com/compiz-reloaded/compiz/issues/70"```

**Comment by gianlucapettinello** [comment]
Perfect. It works! Thanks a lot
The next step is for me to have big shadows (mac styles). With compiz 0.9 series I used to modify the corresponding meta data file increasing the max radius to 60. But here it is not the case.
Please could you help me?
Should I file a feature request?

Thanks
Gianluca

**Comment by raveit65** [comment]
In decoration-plugin you can setup the window-shadow.
