### ISSUE TITLE
Compz install does not work for powerPC

### ISSUE THREAD

**Issue by plopmw** [compiz-reloaded/compiz#72]
installation of compz on debian jessie on a powerpc5,4 fails:

root@Ludvico# wget -q http://download.tuxfamily.org/compiz/apt/key.pub -O- | apt-key add - && echo "deb http://download.tuxfamily.org/compiz/debian $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/compiz-debian.list && apt-get update
OK
deb http://download.tuxfamily.org/compiz/debian jessie main

...
...

Get:18 http://ftp.uk.debian.org jessie/main Translation-en [4,583 kB]                                         
Get:19 http://ftp.uk.debian.org jessie/non-free Translation-en [72.1 kB]                                      
Fetched 18.7 MB in 32s (578 kB/s)                                                                             
W: Failed to fetch http://download.tuxfamily.org/compiz/debian/dists/jessie/InRelease  Unable to find expected entry 'main/binary-powerpc/Packages' in Release file (Wrong sources.list entry or malformed file)

W: Failed to fetch http://ppa.launchpad.net/teejee2008/ppa/ubuntu/dists/jessie/main/binary-powerpc/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
root@Ludvico# apt-get install compiz
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package compiz is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'compiz' has no installation candidate

not sure where to go from here...

**Comment by ethus3h** [comment]
Doesn't look like anything's wrong with Compiz... just a matter of that package repository not having ppc builds I think (thus necessitating building it yourself or asking the repository maintainers to add them)

**Comment by plopmw** [comment]
Ah, thats a pain, thanks!

**Comment by ethus3h** [comment]
Np. Hopefully whoever's in charge of that notices this issue and adds builds :)

**Comment by plopmw** [comment]
On Sunday 07 May 2017 16:17:14 Elliot Chandler wrote:
> Np. Hopefully whoever's in charge of that notices this issue and adds 
builds
> :)

as a newby, the green download code button does not ssem to do 
anything, 

what would be he #git commant to get the debian compiz?

Can I as this kind of thing to a stranger? ;-)

many thanks for your quick responses

Frans

**Comment by ethus3h** [comment]
(I'm afraid I can't give you a quick response on that, since I don't know how to do that in Debian (I could help if it were Gentoo, but...). Regarding the button not working, maybe it requires JavaScript? In any regard, good luck!)

**Comment by soreau** [comment]
the download button should have a URL to use with `git clone URL`
