### ISSUE TITLE
`compiz-gtk` in Debian repo and MATE 1.18

### ISSUE THREAD

**Issue by marsjaninzmarsa** [compiz-reloaded/compiz#73]
`compiz-gtk` 0.8.12.3-0~jessie1 (current upstream for Jessie) depends on `libmarco-private0`, but MATE 1.18 uses `libmarco-private1` (which are in conflict).

Related to #69.

**Comment by XRevan86** [comment]
The [repository](http://compiz-debian.tuxfamily.org/) is out of the scope of our control.
@elgeneralmidi is the person behind it and may be he will be notified by this mention.

Either way, this is not a bug in Compiz Reloaded per se, so… closing.

**Comment by marsjaninzmarsa** [comment]
I've found this on repository webpage:
> If you have an issue or a bug, please let us know. You can report directly on [Github](https://github.com/compiz-reloaded) in the appropriate section by application or contact the admin of this project by email (see the contact in GPG Key).

Little misleading. :wink: 
I'll try to reach him by email I think.

**Comment by marsjaninzmarsa** [comment]
Aaaand no response until now. :cry:
