### ISSUE TITLE
Some dialog windows very slow to appear

### ISSUE THREAD

**Issue by lukefromdc** [compiz-reloaded/compiz#74]
Certain dialog windows are very slow to appear with compiz-reloaded. Both the Caja and Nemo confirm delete dialogs are slow to appear, and the force quit confirmation dialog window from the mate panel "force quit" applet is another offender. In some cases the dialog window is so slow to appear as to seem "lost."

 Also, in some cases right- clicking on a caja desktop will create a new folder without the right-click menu ever appearing. Most of the time the menu shows up but occasionally a folder is generated directly.

This is on Debian Unstable using a Radeon HD 6750 and the r600g Mesa driver borrowed from the Ubuntu "oibaf" Mesa ppa. On compiz 0.9.13 the above issue never appears. I am now testing them side by side because Ubuntu is moving on to GNOME and Wayland and I wonder if compiz 0.9 branch has a future

**Comment by soreau** [comment]
I'm not sure about caja and nemo but the force-quit dialog happens some time after an application stops responding to pings from the (X) server so a delay is expected there.

So far as the right-clicking problem, I haven't noticed it here in xfce. Is the first item in the right-click menu create folder? Perhaps whatever application is responsible is creating the menu under the mouse (or the mouse is moving SW) and the un-click triggers the first item in the menu list. That's just a guess of what might be happening.

The drivers shouldn't matter regarding these types of issues.

**Comment by lukefromdc** [comment]
The force-quit dialog I am referring to is not the one coming up automatically from an unresponsive program but rather the one invoked by the mate-panel "force-quit" applet, which in compiz 0.9 comes up immediately after clicking on the program to be terminated by the applet. The right-click problem on the  caja desktop is intermittant, most of the time it works OK but sometimes it acts up.

**Comment by soreau** [comment]
Can you possibly try the patch referenced in #77?

**Comment by lukefromdc** [comment]
I will test that tonight after an event I shortly must leave to attend.

**Comment by lukefromdc** [comment]
Just tested this, there are still a few slow dialogs (especially a delete dialog run from Nemo as root) but many dialogs that used to be delayed now come up instantly and caja's delete dialog either comes right up or is delayed a second but no more.

**Comment by soreau** [comment]
So the situation improved but not totally fixed. Can you try [this patch](http://sprunge.us/AATc) on top of latest master?

**Comment by lukefromdc** [comment]
The delete dialogs in both nemo and caja are not consistant in how fast they come up, sometimes right quick and sometimes still delayed, usually by about a second but occasionally by more.. the mate-panel shutdown applet dialot now comes up instantly, every time.

Leaving this installed for testing for now

**Comment by lukefromdc** [comment]
mate-panel "force-quit" comes up instantly

**Comment by lukefromdc** [comment]
I'll test that when I get home, on top of current changes from master plus
the gtk-frame-extents fix I always use in any version of compiz

**Comment by lukefromdc** [comment]
That got it, now the delete and compress dialogs in Nemo and Caja come right up. I now have a nice, usable install of compiz with this and https://github.com/compiz-reloaded/compiz/pull/8 applied to today's git master.

**Comment by soreau** [comment]
I noticed some crashes on compiz startup with that patch, could I trouble you to try [this patch](http://sprunge.us/ZPej) instead on top of current master? If it works we can put this one to sleep hopefully.

**Comment by soreau** [comment]
I noticed some crashes on compiz startup with that patch, could I trouble you to try [this patch](http://sprunge.us/ZPej) instead on top of current master? If it works we can put this one to sleep hopefully.

**Comment by lukefromdc** [comment]
OK, I can confirm http://sprunge.us/ZPej also works, same results with the dialogs as with the previous patch http://sprunge.us/AATc

**Comment by soreau** [comment]
Ok, thanks for testing.
