### ISSUE TITLE
Sometimes icon does not appear on DnD cursor in Dnd operations

### ISSUE THREAD

**Issue by lukefromdc** [compiz-reloaded/compiz#75]
In some but not all drag and drop operations, the cursor never "picks up" the icon but can still "drop" it in the desired location. The cursor itself changes to the hand and arrow used in my cursor theme always, but the icon only appears on it some of the time.

This is on Debian Unstable using a Radeon HD 6750 and the r600g  Mesa driver borrowed from the Ubuntu "oibaf" Mesa ppa. On compiz 0.9.13 the above issue never appears.

**Comment by soreau** [comment]
Is there a case where this consistently happens? If so, what steps are required to reproduce the problem? What desktop environment are you using?

**Comment by lukefromdc** [comment]
This is in MATE, it is never consistant. I have mostly noticed this in Caja, when dragging an icon within the desktop or between folders. It happens some of the time but not all of the time.

**Comment by soreau** [comment]
Do the latest commits help this problem by chance?

**Comment by lukefromdc** [comment]
I haven't seen this bug back since I switched over to compiz-reloaded a few days ago, it may be gone. I will let you know if it returns
