### ISSUE TITLE
Feature request: Bigger resolution of MIPMAP blur effect rendered texture

### ISSUE THREAD

**Issue by Meitoncz** [compiz-reloaded/compiz#76]
Hi,

I would love to have nice "non-pixelated" blur visuals under semi-transparent elements.
At the moment blur has really poor quality while using mipmap blur and you can see pixelated artifacts when using the effect.

I am not sure if it is clear what I mean, I will explain further if needed.

Many thanks.

Meiton

**Comment by soreau** [comment]
Perhaps a screenshot would help

**Comment by Meitoncz** [comment]
sure, there you go.

![compiz blur resolution poor](https://user-images.githubusercontent.com/7557451/28078445-679f6f68-6654-11e7-8571-38b9cb6d7202.png)

You can see that "square-pixelated" blur, which is not really nice in my opinion.
It seems like what the mipmap blur does is it blur all stuff behind semi-transparent elements, but output is really low-res and it is being zoomed to fit in a view.

To be honest, I would love to have this effect pretty and smooth, but that is probably just my OCD thing and average user doesnt give a damn.

Also I think it would take some time to rewrite it so it would work like I would prefer (targeting to have same blur effect as on macOS).


Thank you.


Meiton

**Comment by soreau** [comment]
Is Gaussian any better for you?

**Comment by Meitoncz** [comment]
Well, I would say Gaussian is a little smoother, but I prefer Mipmap because of its strength, Gaussian effect is just very confusing.

**Comment by Meitoncz** [comment]
This is gaussian, when I set it on "max", the artifacts are visible as well.

![gaus](https://user-images.githubusercontent.com/7557451/28080752-86aff460-665c-11e7-987d-127336812591.png)

**Comment by soreau** [comment]
Have you tried adjusting Mipmap LOD?

**Comment by Meitoncz** [comment]
Yes, i did, actually I am using Mipmap LOD on 6.7, which is better and the issue is not that visible, but it is still slightly there. I know that this is probably how the algoritgm just works and not bug, I would just love to see to get this effect improved in the future so I would use smaller value for Mipmap LOD with better results (like on macOS, as I mentioned before).

I would code it myself if I would know how to, it is very important for me as I have a little problem with my perfectionism, even it is very "dumb/not that much" an issue for most users.

**Comment by soreau** [comment]
Yes, I think this is how it's intended to work. There are probably better blurring algorithms out there - as always, patches welcome.

**Comment by ethus3h** [comment]
IMO, the real solution to this is to increase the maximum value of the Gaussian Radius field, which is something I've been meaning to do at some point. I don't know if that will need any code changes, though.

**Comment by soreau** [comment]
@ethus3h You would only need to change [the metadata](https://github.com/compiz-reloaded/compiz/blob/master/metadata/blur.xml.in#L75).

**Comment by ethus3h** [comment]
Ok, cool, thanks :D I hadn't taken the time to look into the code to check if there was any technical restraint on bumping it :P

**Comment by ethus3h** [comment]
I just tested with [these changes](https://github.com/compiz-reloaded/compiz/compare/master...ethus3h:blur-max-2017jul11?expand=1) and can't see any difference between radius=15 and radius=128, so I don't think that strategy alone will work :( I think I'll need to learn more about how blurring algorithms in general work, and also how this code in specific works, to be able to finish this...

I probably won't do that soon, since there are more pressing things to try to figure out, sorry :P

**Comment by ethus3h** [comment]
Ok, I just missed something simple in the patch, and have made a patch that does allow larger blur sizes to take effect. However, it crashes with large blur sizes. I haven't investigated this yet.

[Patch](http://futuramerlin.com/issue-tracker/file_download.php?file_id=79&type=bug)
[Backtrace](http://futuramerlin.com/issue-tracker/file_download.php?file_id=78&type=bug)
