### ISSUE TITLE
Qt5 (sub-)menus sometimes are shown with delay

### ISSUE THREAD

**Issue by tsujan** [compiz-reloaded/compiz#77]
First, I wanted to thank you for continuing the development of this excellent x11 compositor. I happily use it with LXQt for a year (I discovered your work only a year ago).

Sometimes, Qt5 menus and, especially submenus, are shown with a 1-2 sec delay. If I move the cursor to where a submenu/menu should appear, it'll appear almost instantly but if not, it might have a 1-2 sec delay.

I've seen the same behavior in a few gtk apps too -- for example, in combo menus of easystroke -- but it mostly happens with Qt5. It doesn't happen with kwin or other compositors. It doesn't happen with Qt4 either (although Qt4 isn't used anymore).

Sorry, I'm not familiar with the Compiz code (yet?), so I don't have any clue as to which part of Compiz is responsible for this.

**Comment by ruegerjr** [comment]
I notice this same problem as well.  2 second delay is not an exaggeration, but in my case, this only occurs about 25% of the time.

1) It occurs in both QT5 and GTK3 windows, but NOT GTK2.
2) It does NOT happen on my system with Compiz 0.9.13
3) It occurs with both nouveau and proprietary nvidia drivers for my nvidia hardware, 
4) It occurs  in both XFCE and LXQT environments.
5) It occurs for both drop-down and pop-up (right-click) menus.  Both left-clicking and mouse-over on a menu bar will show it. 
6) It occurs in both Void Linux and Arch Linux

**Comment by ruegerjr** [comment]
This bug may be duplicate, or at least related to #74

**Comment by tsujan** [comment]
@ruegerjr Here, it occurs only with popus -- menus or combo popups -- and, as you mentioned, it's random.

Qt5's methods for creating/showing windows are very different from those of Qt4. Somehow, Compiz can't handle this difference efficiently.

**Comment by ruegerjr** [comment]
With difficulty, and animations off, I compiled and ran compiz 0.8.8, (which of course pre-dates qt5 and gtk3). This bug occurs in much the same way, and is assumed NOT RELATED TO REVISIONS SINCE Compiz 0.8.8.  I found no obvious duplicate bug complaints in the 0.9 branch, and yet 0.9.13 does not have this bug.  By accident or intention, they have made some change that prevents this.

**Comment by rbn42** [comment]
In `kate`, when I opened the `file` menu, and pressed left arrow key to move the cursor to `help` menu, this delay occurs. But if i press down arrow key immediately after left arrow key, then the sub-menu will show without delay.
Can you reproduce this behavior? 
My guess about this behavior is the menu window was created without delay, but the corresponding X window mapping event was not correctly handled. Pressing down arrow key immediately after left arrow key triggered another X window event and thus forced the window manager to show the sub-menu without delay.

**Comment by tsujan** [comment]
@rbn42 Your finding is similar to what I told about moving the cursor to where a submenu/menu should appear. I've got a habit to do so under Compiz ;)

I wanted to look into Qt's x11 code but, when I saw the same thing in Firefox, I concluded that this should be an issue in Compiz. It also happens with Qt combo popups when they are NOT drawn as menus.

**Comment by rbn42** [comment]
@tsujan Thanking you for clarifying :) 
BTW, I also have a habit to maximize window with Ctrl+Space+X. With marco-gtk3, the maximizing still happens instantly even though the menu is shown with delay.

**Comment by soreau** [comment]
I definitely can reproduce this problem and have tried debugging it before but this one is tricky. Here are the knowns so far:

The 'windows' in question are override-redirect. eventLoop() at [event.c:1355](https://github.com/compiz-reloaded/compiz/blob/master/src/event.c#L1355) calls mapWindow() defined at [window.c:2537](https://github.com/compiz-reloaded/compiz/blob/master/src/window.c#L2537), however the window is not displayed at this point. The window is shown when [window.c:1465](https://github.com/compiz-reloaded/compiz/blob/master/src/window.c#L1465) bindWindow() gets called from [paint.c:1207](https://github.com/compiz-reloaded/compiz/blob/master/src/paint.c#L1207) in DrawWindow(). At the time of mapWindow(), the CompWindow is usually already created and in the s->windows list and w->texture->pixmap is invalid (which is what we want). The same CompWindow is often reused for all these types of windows. It doesn't seem to matter if the window is created with addWindow() or reused and mapped. DrawWindow() is continuously called to redraw windows and this is the only place bindWindow() is called, conditionally if (!w->texture->pixmap) [paint.c:1207](https://github.com/compiz-reloaded/compiz/blob/master/src/paint.c#L1207).

After some tests, it seems after mapWindow() and before the next call to DrawWindow(), the window is being removed from the s->windows list and later bound at the time it is re-added, without the use of unhookWindowFromScreen() / insertWindowIntoScreen(). These assumptions might not be completely accurate and I haven't been able to pinpoint yet, where the window is removed/readded to s->windows list.

**Comment by soreau** [comment]
I cobbled together this hack after tracking the issue to a function being called on timeout, syncWaitTimeout(). Please test [this patch](http://sprunge.us/jghN).

**Comment by tsujan** [comment]
Wow! Thank you very much! I'll test it tomorrow.

**Comment by ethus3h** [comment]
Patch seems to fix the issue here. Thanks! :D

**Comment by tsujan** [comment]
Couldn't wait until tomorrow... the patch works like a charm: Qt5 menus are agile now -- and the same for combo (non-menu) popups. Thanks again!

I think this can be closed.

**Comment by soreau** [comment]
Glad to hear it fixes the problem for you guys. I plan to try a few things locally before deciding exactly what to push. Thanks for the quick tests.
