### ISSUE TITLE
Various bugs in compiz in Manjaro XFCE

### ISSUE THREAD

**Issue by darcn181** [compiz-reloaded/compiz#78]
I want to report some bugs that are a bit different but they are really annoying

> The first one is that if i scroll down in some gtk2 apps sometimes it will make a distort effect depending on the direction to where i am scrolling. I have confirmed that this only happens with compiz because i tried this with xfwm4 and nothing happened.
![captura de pantalla_2017-08-01_14-52-19](https://user-images.githubusercontent.com/28988467/28842587-2e497cda-76cc-11e7-935e-4d969c71516a.png)

> The second one is a little bit different being that if i want to select a custom color in ccsm(gtk3) for the resize plugin and put a color that has saturation even if it has the lowest opacity, it will display the color too bright making it completely different from the one i chose before(i'm going to try if it is the ccsm-gtk3 by seeing if with the gtk2 version everything is normal).
![captura de pantalla_2017-08-01_15-18-35](https://user-images.githubusercontent.com/28988467/28842898-61cde9be-76cd-11e7-9392-51195256f1ff.png)
![captura de pantalla_2017-08-01_15-21-44](https://user-images.githubusercontent.com/28988467/28842899-6207285a-76cd-11e7-994a-436f9012d3aa.png)

- The third one being that i can't change my gtk-window-decorator theme no matter what i do and with what flag i use when compiling it(using compiz-gtk-git from aur).

**Comment by soreau** [comment]
The first one is a driver problem. See https://github.com/compiz-reloaded/compiz/issues/56

The second one might also be a driver bug. Do you have similar effect when using opacity, brightness and saturation plugin to make a window partially transparent?

For the third issue, you have to set marco use flag (manually?), see https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=compiz-core-git

**Comment by soreau** [comment]
I was able to fix the second problem with a310da7

**Comment by darcn181** [comment]
Thanks for that fix, and it seems that compiling the compiz-core-git package with the flag fixes the border problem, the only problem that persists is the gtk2 apps, you should take a look at the code of the normal compiz because in there the bug is not present and it only appears with this compiz, when you fix that gtk2 bug i'm going to make a tutorial in the manjaro forums, thanks for everything.

**Comment by soreau** [comment]
< repeated >The first one is a driver problem. See #56 < /repeated >

**Comment by darcn181** [comment]
It seems that if i use fix window refresh in xgl with fglrx in the solutions plugin it fixes the problem but it makes the pc go slow as hell making the animations that without it are at 60fps or more but if i activate it, it will make those animations go to 15 fps.

**Comment by soreau** [comment]
Which graphics driver are you using? If intel, I think the intent is to use the modesetting driver instead of intel.

**Comment by darcn181** [comment]
Yes i am using video intel but i really think you should look into it or something, when you fix that issue i'm going to close down this thing and if i find another issue i'll let you know in here if i hadn't close this thing.
