### ISSUE TITLE
Artifacts when scrolling and big border around gtk3 apps

### ISSUE THREAD

**Issue by gianlucapettinello** [compiz-reloaded/compiz#79]
I've installed compiz 0.8 in xfce after long time with compiz 0.9 series. I've intel driver. As written in the title I observe artifacts when scrolling in programs like thunar, geany and so on. This was not the case. Besides in gtk3 apps there is a big black border around the window and then there is the shadow. With compiz 0.9 series this is not the case.
Please could you help me?

Thanks a lot
Gianluca

**Comment by soreau** [comment]
You might try the modesetting driver as described in #56. The black border has to do with #8.

**Comment by gianlucapettinello** [comment]
Yes I will try with modesettings even though it looks that it consumes more battery than intel driver. The problem is that neither compiz 0.9 nor xfwm4 have this issue despite intel driver. No other fix? Could it be a problem of vsync?

Thanks

**Comment by soreau** [comment]
I don't know why this wouldn't happen with 0.9 compiz.

**Comment by gianlucapettinello** [comment]
I'll try to get a look to the code. Could it be due to the way damage is treated

**Comment by soreau** [comment]
This apparently is a relatively new bug and doesn't happen with other drivers.. it might be useful to attempt bisecting the xf86-video-intel driver, you'd just need to find one good commit to start.

**Comment by tsujan** [comment]
For the record:

`xf86-video-intel` was very buggy with a relatively new Lenovo Ideapad. Once I removed it and used modesetting (automatically), all graphical problems disappeared and Compiz (and all other apps that needed compositing) started to work like a charm.

`xf86-video-intel` worked OK with an older Asus laptop but modesetting was as good as it, at least.

**Comment by soreau** [comment]
Closing this as NOTOURBUG.
