### ISSUE TITLE
Panel gets pixelated after resizing a window using the rectangle or line mode

### ISSUE THREAD

**Issue by darcn181** [compiz-reloaded/compiz#81]
Basically the title is self explanatory
Using normal or stretch mode fixes it!
![captura de pantalla_2017-08-06_16-19-50](https://user-images.githubusercontent.com/28988467/29006748-f517d2a8-7ac3-11e7-8b62-b1464a6c2eef.png)
Here's a picture while using the rectangle or line mode in the resize plugin
![captura de pantalla_2017-08-06_16-20-12](https://user-images.githubusercontent.com/28988467/29006749-f51e48b8-7ac3-11e7-9e75-a234adcdddca.png)
How to Reproduce: 

1. Activate resize plugin(even though it can't be disabled in ccsm since it re-enables by itself)
2. go to general and in "Way of resizing by default(or something i don't know because my ccsm is in spanish)" change from normal or any other option to line or rectangle
3. resize a window
4. maximize the window and everything on the panel should be pixelated.
Plus: I would like that the scale plugin gives you the minimized windows instead of hiding them.

**Comment by soreau** [comment]
You never said what panel you're using. It doesn't seem to happen with xfce4-panel and I can't really see any pixelation in the shots you provided.

**Comment by ethus3h** [comment]
@soreau: Compare the "A" at the leftmost side of the panel between the two screenshots, zoomed in.  It does look kind of different, like it's got a black border around it or something.

IDK what the issue is though, I don't think I've seen that before (IDK what panel app it is either).

**Comment by ethus3h** [comment]
@soreau: Compare the "A" at the leftmost side of the panel between the two screenshots, zoomed in.  It does look kind of different, like it's got a black border around it or something.

IDK what the issue is though, I don't think I've seen that before (IDK what panel app it is either).

**Comment by darcn181** [comment]
I'm using the xfce panel and yes the global menu gets pixelated and i thought it was the applet but then i saw the icons at the right and everything look pixelated, even the close buttons. I'm able to pixelate everything over and over until i restart compiz or just use the normal or stretch option.

**Comment by soreau** [comment]
I didn't notice this before but in the first two screenshots, it appears that the window decoration is part of the titlebar in one of the shots.. how is that happening? It looks like this might be the cause of the issue? but what does that have to do with the resize mode? a misnomer perhaps?

**Comment by ethus3h** [comment]
FWIW, I had my KDE set up like that for a while just by setting in winrules to not decorate maximized windows, and adding window controls widget to the panel. Perhaps this is a similar setup??

**Comment by darcn181** [comment]
I use !state=maxvert in window decorations plugin so i save space and a plugin for xfce panel that puts the buttons for maximize and bla bla bla, i tried compiz in default settings and the problem happened.I installed the stable version of CR and the bug wasn't reproducible in there.

**Comment by darcn181** [comment]
I started testing the commits that were applied since the latest stable release and found out that the commit a310da7f4b801ca110068a2900af3afa68313c53 is the one that is causing the bug, this isn't confirmed though, i'll keep testing tomorrow and post the results here

**Comment by soreau** [comment]
If that is the bad commit, see if [this patch](https://gist.github.com/soreau/3540a1ed099c1b03fbc53665b89f91ca) helps.

**Comment by darcn181** [comment]
It seems that the patch fixes the issue, thanks!
