### ISSUE TITLE
Window decoration not painted (just white area) but working

### ISSUE THREAD

**Issue by styxxx** [compiz-reloaded/compiz#82]
Hi,

I know what you think "emerald isn't running or the window decoration plugin is disabled". No, not the case ;) 

Emerald is running without error message, the decoration plugin is activated. The space for the window decoration is reserved (and changes its sitze when I select another theme) bust just filled with white color. Besides not being visible the decoration actually works: I can move the mouse over the position where the buttons are supposed to be and I get the correct tool tip. Pressing the insivible button (for example to minimize the window) also works.
So the decoration is there - but just not visible. 

Restarting emerald and/or compiz or switching to another emerald theme doesn't fix the problem. There are no messages on the console and no log file entries.

One interesting thing: if I activate the "reflection" plugin the decoration turns black. 

Installed packages:

ii  compiz-reloaded                                                  0.8.14-0~stretch1                      all          OpenGL window and compositing manager
ii  compiz-reloaded-bcop                                             0.8.14-0~stretch1                      all          Compiz Reloaded option code generator
ii  compiz-reloaded-core                                             0.8.14-0~stretch1                      amd64        OpenGL window and compositing manager
ii  compiz-reloaded-dev                                              0.8.14-0~stretch1                      amd64        OpenGL window and compositing manager - development files
ii  compiz-reloaded-gtk                                              0.8.14-0~stretch1                      amd64        OpenGL window and compositing manager - Gtk window decorator
ii  compiz-reloaded-mate                                             0.8.14-0~stretch1                      amd64        OpenGL window and compositing manager - MATE window decorator
ii  compiz-reloaded-plugins                                          0.8.14-0~stretch1                      amd64        OpenGL window and compositing manager - plugins
ii  compiz-reloaded-plugins-experimental                             0.8.14-0~stretch1                      amd64        Compiz Reloaded plugins - "unsupported" collection
ii  compiz-reloaded-plugins-extra                                    0.8.14-0~stretch1                      amd64        Compiz Reloaded plugins - extra collection
ii  compiz-reloaded-plugins-main                                     0.8.14-0~stretch1                      amd64        Compiz Reloaded plugins - main collection
ii  compizconfig-settings-manager-reloaded                           0.8.14-0~stretch1                      amd64        Compizconfig Settings Manager
ii  emerald                                                          0.8.14-0~stretch1                      amd64        Decorator for compiz-reloaded
ii  libcompizconfig-reloaded-0                                       0.8.14-0~stretch1                      amd64        Configuration settings library for compiz-reloaded
ii  libemeraldengine0                                                0.8.14-0~stretch1                      amd64        Decoration engines for compiz-reloaded
ii  python-compizconfig-reloaded                                     0.8.14-0~stretch1                      amd64        Compizconfig bindings for python
ii  emerald                                                          0.8.14-0~stretch1                      amd64        Decorator for compiz-reloaded
ii  emerald-themes                                                   0.8.14-0~stretch1                      all          Themes for emerald window decorator
ii  libemeraldengine0                                                0.8.14-0~stretch1                      amd64        Decoration engines for compiz-reloaded

XServer:

ii  x11-xserver-utils                                                7.7+7+b1                               amd64        X server utilities
ii  xserver-common                                                   2:1.19.3-2                             all          common files used by various X servers
ii  xserver-xephyr                                                   2:1.19.3-2                             amd64        nested X server
ii  xserver-xorg                                                     1:7.7+19                               amd64        X.Org X server
ii  xserver-xorg-core                                                2:1.19.3-2                             amd64        Xorg X server - core server
ii  xserver-xorg-input-evdev                                         1:2.10.5-1                             amd64        X.Org X server -- evdev input driver
ii  xserver-xorg-input-mouse                                         1:1.9.2-1+b1                           amd64        X.Org X server -- mouse input driver
ii  xserver-xorg-input-synaptics                                     1.9.0-1+b1                             amd64        Synaptics TouchPad driver for X.Org server
ii  xserver-xorg-input-wacom                                         0.34.99.1-1                            amd64        X.Org X server -- Wacom input driver
ii  xserver-xorg-legacy                                              2:1.19.3-2                             amd64        setuid root Xorg server wrapper
ii  xserver-xorg-video-ati                                           1:7.9.0-1                              amd64        X.Org X server -- AMD/ATI display driver wrapper
ii  xserver-xorg-video-mach64                                        6.9.5-1+b2                             amd64        X.Org X server -- ATI Mach64 display driver
ii  xserver-xorg-video-r128                                          6.10.2-1                               amd64        X.Org X server -- ATI r128 display driver
ii  xserver-xorg-video-radeon                                        1:7.9.0-1                              amd64        X.Org X server -- AMD/ATI Radeon display driver

Debian stretch, 4.12.0-1-amd64 #1 SMP Debian 4.12.6-1 (2017-08-12) x86_64 GNU/Linux

**Comment by soreau** [comment]
At first thought, it sounds like a problem with the graphics driver stack. Does it make a difference if you try starting compiz with --indirect-rendering option?

**Comment by styxxx** [comment]
If I use the --indirect-rendering option compiz fails to start:

compiz (core) - Fatal: No valid GL extensions string found.
compiz (core) - Error: Failed to manage screen: 0
compiz (core) - Fatal: No manageable screens found on display :0

(I also tried "LIBGL_ALWAYS_INDIRECT=1 INTEL_BATCH=1 compiz --replace --indirect-rendering --sm-disable ccp &" like I found in some wiki with the same result). Hmm... :-?

**Comment by soreau** [comment]
Can you post your /var/log/Xorg.0.log file and the output of `glxinfo|grep renderer`?

**Comment by styxxx** [comment]
[Xorg.0.log.txt](https://github.com/compiz-reloaded/compiz/files/1286322/Xorg.0.log.txt)


glxinfo | grep renderer:
> 
>     GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
>     GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
> Extended renderer info (GLX_MESA_query_renderer):
> OpenGL renderer string: Gallium 0.4 on AMD PALM (DRM 2.50.0 / 4.12.0-1-amd64, LLVM 3.9.1)
> 

Thank you :)

**Comment by soreau** [comment]
Things appear to be in order. I've noticed some decoration corruption with DRI3 but not white as you describe. Does it make a difference using DRI2 instead of 3?

**Comment by styxxx** [comment]
Setting xorg.conf to dri2 works! Some themes still seem to look a bit off (like Orangeglass - at least I think) but they're visible now. 

I attached screenshots with dri3 and dri2. And the current (working) xorg.conf.

![dri3](https://user-images.githubusercontent.com/13952709/30189877-e714f5a0-9436-11e7-8086-d789b8853c97.png)
![dri2](https://user-images.githubusercontent.com/13952709/30189876-e7130236-9436-11e7-93ae-b6a214366923.png)
[xorg.conf.txt](https://github.com/compiz-reloaded/compiz/files/1286371/xorg.conf.txt)

**Comment by soreau** [comment]
Great, now you have enough to file a bug at bugs.freedesktop.org, probably under DRI>DRM/Radeon. I'm closing this for now since it's not a compiz bug but you can still respond further to this issue if needed.

**Comment by styxxx** [comment]
Thank you! 

If you're interested: https://bugs.freedesktop.org/show_bug.cgi?id=102599
Seems to be a problem with the "ShadowPrimary" Option.

And thanks for your great job on this project! :)
