### ISSUE TITLE
Compiz Mate: Move with window within the wall is not working

### ISSUE THREAD

**Issue by renelabounek** [compiz-reloaded/compiz#83]
I have installed Mate GUI and compiz at Debian Jessie and moving with window within the desktop wall is not working to me.

Mate, I have installed with following command:
`sudo apt-get install mate-desktop-environment-extras`

Compiz, I have installed with following manual:
[http://compiz-debian.tuxfamily.org/](url)

As you can see on following image, I have set the keyboard shourtcuts for moving with window within the wall. But is is not working. Of course, the Desktop Wall is activated.
[https://i.imgur.com/UZGkwwx.png](url)

When I switch from compiz mode to the marco mode. The CTRL+ALT+SHIFT+ARROW shortcuts work well. I am using same compiz function on Ubuntu Mate on my notebook without any troubles.

Please, does anybody have some idea?
Regards,
Rene

**Comment by soreau** [comment]
@renelabounek Presumably 'move within wall' without a window works? What do you have set for vertical and horizontal viewports in ccsm>General Options>Desktop Size? I tested briefly here and 'move with window within wall' is working. Maybe try using a different key binding to see if something might be blocking the combo.

**Comment by renelabounek** [comment]
@soreau Thanks, you are right, Debian has the problem with the combo Ctrl+Shift+Alt+Arrow. I have switched it on Ctrl+Shift+Arrow and it works suddenly. Beside the complication that I have to learn new combo, other question raised: Why Debian has the problem?

**Comment by soreau** [comment]
@renelabounek It might have something to do with your desktop environment preserving the binding somehow. Closing this since it's not a problem with compiz.
