### ISSUE TITLE
Gnome apps like Nautilus not using compiz window decorator

### ISSUE THREAD

**Issue by arifcatalyst** [compiz-reloaded/compiz#84]
Nautilus not using compiz window decorator but other gnome apps have no issue like gnome-system-monitor. 
![screenshot_2017-09-29_19-54-35](https://user-images.githubusercontent.com/26674272/31020261-1d8dcc68-a550-11e7-8302-0e57f911cf96.png)

**Comment by ethus3h** [comment]
(I thought I'd reported this problem earlier, but apparently not, since I can't find it.)

I think this is caused by the apps using "client-side decorations", and there not being an option to decorate such windows.

**Comment by soreau** [comment]
@ethus3h is right, CSD is not a compiz bug. You might check with the toolkit (gtk/qt/etc) to see if there is a way to disable CSD.

**Comment by ethus3h** [comment]
This inspired me to look into it, and it looks like https://github.com/PCMan/gtk3-nocsd should fix this. I haven't rebooted to test it since I installed it, but it looks encouraging. :D
