### ISSUE TITLE
[0.8.14] Problem with libdecoration.so: : undefined symbol: decor_property_get_type

### ISSUE THREAD

**Issue by Myu-Unix** [compiz-reloaded/compiz#86]
Hello there !

First, let me thank you for your great work on compiz-reloaded, I'm running 0.8.12.x since it came out and it's a joy to use, kudos to you :)

I'm trying to put together ebuilds for 0.8.14 on Gentoo, after installing all prerequisites, I build and install compiz 0.8.14 itself and start it with `compiz --replace`, I receive this error :

`compiz: symbol lookup error: /usr/lib64/compiz/libdecoration.so: undefined symbol: decor_property_get_type`

Looking further in my /usr/lib64 folder, I realize there's multiples version of libdecoration.so, one file and two symlinks in /usr/lib64 :

```
-rwxr-xr-x 1 root root 35088 Oct 10 10:36 libdecoration.so.0.0.0
lrwxrwxrwx 1 root root    22 Oct 10 10:36 libdecoration.so -> libdecoration.so.0.0.0
lrwxrwxrwx 1 root root    22 Oct 10 10:36 libdecoration.so.0 -> libdecoration.so.0.0.0
```

And one in /usr/lib64/compiz :

`-rwxr-xr-x 1 root root 31224 Oct 10 10:36 libdecoration.so
`

Their md5 is different, tinkering around, if I do 

```
rm /usr/lib64/compiz/libdecoration.so
ln -s /usr/lib64/libdecoration.so.0.0.0 /usr/lib64/compiz/libdecoration.so
```

compiz is starting (I've wobbly working for instance) but without decorations and through this error :

```
compiz (core) - Error: dlsym: /usr/lib64/compiz/libdecoration.so: undefined symbol: getCompPluginInfo20070830
compiz (core) - Error: Couldn't load plugin 'decoration'
compiz (core) - Error: dlsym: /usr/lib64/compiz/libdecoration.so: undefined symbol: getCompPluginInfo20070830
compiz (core) - Error: Couldn't load plugin 'decoration'
```

Looking at my 0.8.12.3 compiz install, I've also these two libdecoration.so in the same location but it works

Would you have any pointers on why it behaves like this ? Is it an issue on my end (the way I build compiz within my ebuild) ? Any help appreciated

Have a good day !

**Comment by Myu-Unix** [comment]
Hello ethus3h !

I tried as well from your ebuilds and I still have the odd behaviour, emerging emerald-0.8.14 with compiz-0.8.14 already on the system fails with the below compile error amongst others :

```
main.c:632:5: error: too few arguments to function ‘decor_quads_to_property’
     decor_quads_to_property(data, cairo_xlib_surface_get_drawable(d->surface),
```

If I try with compiz-0.8.12.3 installed first (I've custom ebuilds for 0.8.12.x), emerald 0.8.14 compiles properly and I've full compiz functionality.

**Comment by soreau** [comment]
My guess is that you have parts of 0.9 installed somewhere.. make sure to purge the system of all compiz and libdecoration packages first.

**Comment by Myu-Unix** [comment]
Hello soreau,

Yes ! Spot on, they were some remnants of a manual install in /usr/local, many thanks !

I've reinstalled everything from ethus3h ebuilds and I'm now enjoying a full 0.8.14 install :)

@ethus3h : I think a few Gentooers would be happy to benefit from your work on those ebuilds on the main portage tree (see bug https://bugs.gentoo.org/532580) to replace the dying 0.8.8 version which sits there.

Is it something you're interested to do ? If not, would it be ok for me to go through the official Gentoo proxy-maintainer process in order to try to bring these ebuilds (+ any changes/fixes QA would want) to the main portage tree ?

Thank you both for your help on this, much appreciated !

**Comment by ethus3h** [comment]
@Myu-Unix: I'd be glad to have them in the tree, although I don't really know how to get them there... (I'm not an official "Gentoo Developer" or anything, just a normal user).

Most of the paths I've tried following in terms of getting things to happen in Gentoo seem to lead to the bug tracker (which doesn't seem to get much attention), or to the mailing list (which won't let me subscribe/post to it for whatever reason?? Perhaps I should try with a different email address)... Kind of frustrating, so I've pretty much given up on trying to get my fixes into the tree (is there a trick to it? :P) and just maintain them locally instead -_-;

**Comment by Myu-Unix** [comment]
Yes the process feels kind of cumbersome at times (I'm just a user as well and only managed to get 2 fonts on the tree :p) but there's indeed a trick ! 

If you hop on to IRC at [#gentoo-proxy-maint ](https://wiki.gentoo.org/wiki/Project:Proxy_Maintainers) and ask to a dev to take a look at your Gentoo bug, it usually speed up things a lot ! [compiz](https://packages.gentoo.org/packages/x11-wm/compiz) is actually marked as needing a new maintainer so this shouldn't be too hard to get attention :)

**Comment by ethus3h** [comment]
Thanks!
