### ISSUE TITLE
Having Issue with the blur effect.

### ISSUE THREAD

**Issue by 4goodapp** [compiz-reloaded/compiz#87]
Hi, Am Ttrying to replicate [this blur effect](https://i.imgur.com/MnCFa0S.png) using compiz-reloaded:   but I endup with [this](http://i.imgur.com/oA6T6ul.png). The blur effect is applied but icons and text look so "white".

Am I missing something?

**Comment by soreau** [comment]
I can't really see the effect in your blur effect screenshot but I can see the problem in the second shot and it appears to be a possible graphics driver bug.

**Comment by soreau** [comment]
As discussed on IRC, the driver in use was R600 and starting compiz with R600_DEBUG=sbsafemath fixes the white blur effect problem.
