### ISSUE TITLE
tuxfamily compiz repository for debian testing is out-of-sync

### ISSUE THREAD

**Issue by igor-liferenko** [compiz-reloaded/compiz#9]
Hi,

I installed Debian stretch amd64, built 2015-05-16, from http://cdimage.debian.org/cdimage/weekly-builds/amd64/jigdo-dvd/debian-testing-amd64-DVD-1.jigdo.

I tried to install compiz this way:

    wget -q http://download.tuxfamily.org/compiz/apt/key.pub -O- | sudo apt-key add -
    sudo sh -c 'echo deb http://download.tuxfamily.org/compiz/debian stretch main >> /etc/apt/sources.list'
    sudo apt-get update
    sudo apt-get install compiz compiz-mate

But I got this error:

    The following packages have unmet dependencies:
     compiz-plugins : Depends: libpng12-0 (>= 1.2.13-4) but it is not installable

tuxfamily repository relies on libpng12-0, but it is not available in current debian testing.

Regards,
Igor

**Comment by XRevan86** [comment]
@elgeneralmidi, that's for you :-).

**Comment by elgeneralmidi** [comment]
Hi @igor-liferenko @XRevan86,

thanks for the report, debian stretch use a new libpng now. The problem has been corrected with the new package 0.8.12.3 of compiz in my repo. Please update your APT and it will be good.
