### ISSUE TITLE
edge_flip_* functions doesn't seem to work

### ISSUE THREAD

**Issue by nice0051** [compiz-reloaded/compiz#91]
I use compiz-0.8.14 from http://download.opensuse.org/tumbleweed/repo/oss/ on a 64 bit OpenSuse TumbleWeed system with Plasma 5.11.2 desktop from KDE. It works almost perfectly with only some minor problems. One of these is that the edge_flip_pointer, edge_flip_window and edge_flip_dnd fuctions of the Rotate Cube plugin simply don't seem to work. I enable them, but trying to move a window past the right or left edge of the desktop (for example) doesn't cause anything.

Thank you in advance for investigating this problem.

**Comment by soreau** [comment]
In Rotate Cube>Bindings>Rotate Cube, make sure Rotate Flip Left/Right are set to respective edges. This was disabled by default due to people having problems clicking on edges of the screen.

**Comment by nice0051** [comment]
OK, you're absolutely right. Everything works as supposed to. The only problem might be that the parameters you mentioned are not set by default. I think it's confusing. Don't you consider giving it the aforementioned sane default values?

**Comment by soreau** [comment]
Actually I think it was more annoying for users to have a 1px border around the screen that can't be clicked. By setting the default off, users don't have to worry with this problem and if they want it enabled, they can. There was something about this in the 0.8.14 release notes as well.
