### ISSUE TITLE
Is possible swicth theme from marco to metacity?

### ISSUE THREAD

**Issue by bigbruno** [compiz-reloaded/compiz#94]
Is possible use metacity configuration and not marco?

Thanks and congratulations for your work with compiz.

**Comment by soreau** [comment]
Doesn't marco support metacity themes? which would mean gtk-window-decorator supports metacity themes? If this is the case, you'd still have to use the --marco-theme option.

**Comment by bigbruno** [comment]
I'm using the deepin desktop with the compiz, alternating the theme by it's changed the dconf theme setting to the deepin-wm, mutter, and metacity, but it does not change the setting for the marko theme.

If you change the configuration of marko manually in dconf-editor, compiz detects the change and changes the theme as well, but the system configurator does not make the change.

I thought that if it were possible the compiz to detect the metacity configuration would be better integrated into the deepin desktop.

**Comment by soreau** [comment]
I'm not familiar with deepin but it sounds like the problem you're having isn't directly related to compiz. It sounds like compiz is doing better than the 'system configurator' and there could potentially be a plugin created for deepin desktop integration but as far as I know, this plugin does not exist. Either way, I do not consider the problem you're having a compiz bug so closing this for now.
