### ISSUE TITLE
Fatal error when starting OpenGL plugin

### ISSUE THREAD

**Issue by jafetmorales** [compiz-reloaded/compiz#96]
I am using compiz on a Windows Subsystem for Linux. After configuring compiz with ccsm to run with a profile that includes the OpenGL plugin, I proceed to start compiz. But I get the following errors:

> compiz (core) - Info: Loading plugin: opengl
> compiz (core) - Info: Starting plugin: opengl
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast
> Compiz (opengl) - Fatal: Root visual is not a double buffered GL visual
> compiz (core) - Error: Plugin initScreen failed: opengl
> compiz (core) - Error: Failed to start plugin: opengl
> compiz (core) - Info: Unloading plugin: opengl

**Comment by soreau** [comment]
@jafetmorales Hi, it sounds like you're using compiz 0.9.x because opengl is a plugin. compiz-reloaded is the 0.8.x series. We don't develop or support compiz 0.9.x series here. That said, it appears that you are having fundamental environment issues which isn't a compiz bug.
